forbid(
  principal is a in a::"666",
  action in [Action::"action",Action::"action",Action::"action"],
  resource
) when {
  ((true && ((if ((ip("54.54.54.54")).isIpv4()) then [3918638332286744065] else [(-6727636321328236234), (-6727636073941130590)]).containsAll([resource, a::""]))) && (if (if (if true then true else true) then (if true then true else true) else (if true then true else true)) then (if (if true then true else true) then (if true then true else true) else (if true then true else true)) else (if (if true then true else false) then true else (if true then true else true)))) && (if (if (if true then true else true) then (if true then true else true) else (if true then true else true)) then (if (if true then true else false) then false else false) else false)
};
