forbid(
  principal is a in a::"",
  action in [Action::"action"],
  resource == a::"666666NNNNN66"
) when {
  ((true && ((if (resource in resource) then (if true then resource else resource) else (if true then resource else resource)) in (if (resource in resource) then (if true then resource else resource) else (if true then resource else resource)))) && (a::"666666NNNNN66" in a::"666666NNNNN66")) && (if (a::"666666NNNNN66" in a::"666666NNNNN66") then (a::"666666NNNNN66" in a::"666666NNNNN66") else (a::"666666NNNNN66" in a::"666666NNNNN66"))
};
