forbid(
  principal,
  action in [Action::"action"],
  resource
) when {
  ((true && (if (if (if true then true else true) then (if true then true else true) else (if true then true else true)) then (if (if true then true else true) then (if true then true else true) else (if true then true else true)) else (if (if true then true else true) then (if true then true else true) else (if true then true else true)))) && (if (if (if true then true else true) then (if true then true else true) else (if true then true else true)) then (if (if true then true else true) then (if true then true else true) else (if true then true else true)) else (if (if true then true else true) then (if true then true else true) else (if true then true else true)))) && (if (if (if true then true else true) then (if true then true else true) else (if true then true else true)) then (if ((decimal("390636933325614.5543")) == (decimal("506395283615372.2438"))) then (action in resource) else (action in action)) else (a::"\u{1}/6" in Action::"action"))
};
