forbid(
  principal,
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("28102461747918.9503")) == (decimal("-58273764284071.1169"))) then (if true then (decimal("0.1")) else (decimal("2321031310959.7055"))) else (decimal("               "))) == (decimal("       \0\t(\t66676")))) && ((if ((decimal("0.1")) == (decimal("-2385902322.7393"))) then (if true then (decimal("23551374402177.5359")) else (decimal("3148855081990.1183"))) else (decimal("               \0\0\0\0\0\0\0\u{10}         "))) == (decimal("3628388365.9296")))) && false
};
