forbid(
  principal == a::"",
  action in [Action::""],
  resource
) when {
  ((true && ((if (false == true) then (ip("")) else (ip(""))) == (ip(if false then "" else "")))) && ((if ((ip("c3c3:c3c3:c3c3:c3c3:6767:6767:6767:6767/66")) == (ip("0.0.0.0"))) then (if false then (ip("0.0.0.0")) else (ip("0.0.0.0"))) else (if false then (ip("0.0.0.0")) else (ip("255.255.0.0/24")))) == (if ((decimal("0.1")) == (decimal("6.5535"))) then (ip("0.0.0.0")) else (ip("0.0.0.0"))))) && false
};
