@A("")
permit(
  principal,
  action in [fB::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::Es::fB::Action::""],
  resource in fB::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::Es::fB::a::"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
) when {
  true && (((action["BSv012nnv1B4"])["BSv012nnv1B4"]) in ((action["BSv012nnv1B4"])["BSv012nnv1B4"]))
};
