@J09sssss5ksssssss("O\0\0\u{8}6666Rs666")
forbid(
  principal,
  action in [Action::"action"],
  resource
) when {
  ((true && (({"\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{13}AAAAAAAAAAA\n\n\n\n\n\n\n": ip("208.208.208..122")}["\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{13}AAAAAAAAAAA\n\n\n\n\n\n\n"]) == ({"\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{13}AAAAAAAAAAA\n\n\n\n\n\n\n": ip("208.208.208.208")}["\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{13}AAAAAAAAAAA\n\n\n\n\n\n\n"]))) && (({"\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{13}AAAAAAAAAAA\n\n\n\n\n\n\n": decimal("11.8992")}["\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{13}AAAAAAAAAAA\n\n\n\n\n\n\n"]) == (decimal("663636200.6528")))) && false
};
