forbid(
  principal == a::"",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (-1) else (-1)) else (if false then (-1) else (-1))) == (if ((decimal("0.1")) == (-1)) then (-1) else (-1)))) && (false && ((ip("")).isIpv4()))) && ((decimal("6\0\0")).greaterThanOrEqual(if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))))
};
