forbid(
  principal is a in a::"\0",
  action in [Action::"action",Action::"action",Action::"action"],
  resource
) when {
  ((true && ((if ((-55112800557386186) == (-3948812443086080257)) then [] else (principal["Bsss"])).containsAll([]))) && (!true)) && ((if false then (if true then (ip("c900:9365:833:c9:1:30c9:6:6500")) else (ip("166.166.54.54"))) else (if false then (ip("166.166.166.166")) else (ip("0.51.0.201/3")))) == true)
};
