forbid(
  principal,
  action in [Action::"action"],
  resource
) when {
  ((true && ((if false then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))) == (if ((decimal("0.1")).lessThanOrEqual(decimal("0.1"))) then (decimal("6")) else (if false then (decimal("0.1")) else (decimal("0.1")))))) && (resource is a)) && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))) == (decimal("0.1")))
};
