@BsssssF0ssssD("")
@k66666666("")
@k6X000066("")
permit(
  principal == B::a::"",
  action in [B::Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}")) == (decimal("\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}g4069"))) then (if true then (decimal("394621294407711.2259")) else (decimal("-4340\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}ÿ460.381"))) else (if true then (decimal("\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}[\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}")) else (decimal("\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}ÿ921689.4069")))) == (if (true == true) then (decimal("\u{19}\0\0\0\0\0\0")) else (decimal("10779361.2800"))))) && false) && false
};
