permit(
  principal is a in a::"6",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))) == (if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))))) && ((if ((ip("236.194.242.54/18")).isIpv4()) then (-1) else (-1)) == (-1))) && (!(!(!true)))
};
