forbid(
  principal == a::"\n",
  action in [Action::"action"],
  resource == a::"\n"
) when {
  (true && ((if (action in action) then (if false then action else action) else (if false then action else action)) in (if (action in action) then (if false then action else action) else (if false then action else action)))) && ((if (action in action) then (if false then action else action) else Action::"action") in a::"")
};
