@YEEEEE3000("\0\0\0\0MMMMM\0\0\0\0\0\07/")
permit(
  principal in fB::r::r::r::r::r::C::r::r::r::r::r::r::r::r::r::r::Q::fB::a::"\0\0z\0\0\0\0",
  action in [fB::r::r::r::r::r::C::r::r::r::r::r::r::r::r::r::r::Q::fB::Action::""],
  resource in fB::r::r::r::r::r::C::r::r::r::r::r::r::r::r::r::r::Q::fB::a::"\0\0z\0\0\0\0"
) when {
  true && ((principal["BSv012opu100"]) in ((principal["BSv012opu100"])["BSv012opu100"]))
};
