@Fcccccccccc37s("66666&66666666>666\06")
permit(
  principal is a in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource is a
) when {
  true && ({"ncipal_constraint\0\0\0\nint\0\0\0\n6>$668": {"ncipal_constraint\0\0\0\nint\0\0\0\n6>$668": "ncipal_constraint\0\0\0\nint\0\0\0\n6>$668"}} == {"ncipal_constraint\0\0\0\nint\0\0\0\n6>$668": {"ncipal_constraint\0\0\0\nint\0\0\0\n6>$668": decimal("-199648.8705")}})
};
