forbid(
  principal == a::"633333",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (-1) else (-1)) else (if false then (-1) else (-1))) == (if ((decimal("0.1")) == (-1)) then (-1) else (if false then (-1) else (-1))))) && ((if ((ip("4100::1:16f3:b636:ff36")).isInRange(ip("0.0.0.0"))) then (ip("")) else (ip(""))).isIpv4())) && (false == (false == false))
};
