permit(
  principal is r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::B333sFM::r::a in r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::B333sFM::r::a::"pr666",
  action in [r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::B333sFM::r::Action::"action"],
  resource is r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::B333sFM::r::a in r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::B333sFM::r::a::"pr666"
) when {
  (true && (!((r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::B333sFM::r::a::"pr666"["zpd8"]) <= (-(action["zpd8"]))))) && (!((r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::B333sFM::r::a::"pr666"["zpd8"]) <= (r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::B333sFM::r::a::"pr666"["zpd8"])))
};
