permit(
  principal == r::r::r::r::r::r::r::S::"",
  action,
  resource == r::r::r::r::r::r::r::BR::"\t"
) when {
  (true && ((decimal(principal["A"])).greaterThanOrEqual(if false then (if false then (decimal("390633414457229.3120")) else (decimal("390636933325594.2853"))) else (if true then (decimal("-93674872249306.3421")) else (decimal("8646973995917.614")))))) && ((ip(action["B0r0s0000000"])).isIpv4())
};
