forbid(
  principal is a in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource is a in a::"666>66\u{1}\0\0\0\0\0\0[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[\u{10}6zppppepo"
) when {
  (true && (!(128858986646063727 == (!false)))) && (!(([].containsAny([])) || ((decimal("132714489.4464")).greaterThanOrEqual(decimal("-8900377435730775.6432")))))
};
