permit(
  principal,
  action in [Action::"action"],
  resource in a::""
) when {
  ((true && ((if (resource in resource) then (if true then resource else resource) else (if true then resource else resource)) in (if (resource in resource) then (if true then resource else resource) else (if true then resource else resource)))) && ((if (resource in resource) then (if true then resource else resource) else (if true then principal else principal)) in resource)) && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("-636593520975074.7225"))) else (decimal(""))) == (decimal(if true then "" else "")))
};
