permit(
  principal is a in a::"0",
  action in [Action::"action"],
  resource == a::"0"
) when {
  ((true && ((if ((decimal("0.1")).lessThan(decimal("0.1"))) then (decimal("ef\0\0e\0\0\0")) else (decimal(""))) == (if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (decimal("\0\0\0\0\0\0A"))))) && (false == ((ip("")).isIpv4()))) && (false && ((decimal("yyy6\u{1}\0")).lessThanOrEqual(decimal(""))))
};
