@m("")
@r("ct&on_6")
permit(
  principal,
  action in [m::r::Bs0s::m::r::r::r::r::C::K::Bs0s::Action::"action"],
  resource == m::r::Bs0s::m::r::r::r::r::C::K::Bs0s::a::"\u{7}\0\0\0\0\0"
) when {
  (true && (if ((decimal("336663")).lessThanOrEqual(decimal("6"))) then (m::r::Bs0s::m::r::r::r::r::C::K::Bs0s::a::"" in m::r::Bs0s::m::r::r::r::r::C::K::Bs0s::a::"\u{7}\0\0\0\0\0") else ((if false then (decimal("-140828020741.1658")) else (decimal("202883179100.3190"))) == (decimal("6"))))) && (!(m::r::Bs0s::m::r::r::r::r::C::K::Bs0s::a::"" in m::r::Bs0s::m::r::r::r::r::C::K::Bs0s::Action::"action"))
};
