permit(
  principal,
  action == Action::"action",
  resource is a
) when {
  ((true && ((if (principal is a) then (decimal("")) else (decimal(""))).greaterThan(decimal("")))) && ((if ((decimal("6.610")).greaterThanOrEqual(decimal("0.0"))) then 0 else 3904987247140025910) <= (if ((decimal("1525485716507.2694")).greaterThan(decimal("5657647031884.1856"))) then (if false then (-993383745392855498) else 3038287259199220268) else 3689348814791649834))) && ((if false then (decimal("1277.5936")) else (decimal("0.0"))).greaterThanOrEqual(decimal("0.0")))
};
