forbid(
  principal == a::"",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((ip("c3c3:c3c3:c3c3:c3be:c3c3:c3c3:c3c3:c3c3/66")) == (ip("ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff/126"))) then (if true then (ip("c3c3:c3c3:c3ff:ffff:ffff:ffff:ffff:ffff/66")) else (ip("ffff:ffffff::fffffff::ffffffff::ffffffff::1122ffff::fffffff:ffff/126"))) else (ip(""))) == (if ((decimal("44770021111112233444477550033..22557755")) == (decimal("--3332764795055152.6959"))) then (if true then (ip("ffffff:ffffffff::ffffffff::ffffffff:fffffff::fffff::Ã625:25ff")) else (ip("ffff:fffffff:ffffffff::ffffffff::ffffffff::ffffffff::ffffff:ffff/126"))) else (if true then (ip("ffff:ffff::3362255::2255ffff::ffffffff::ffffff::ffff3::11ffÃ/126")) else (ip("ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffc3/126")))))) && ((if ((ip("dada:da36:3636::1:c3c3")) == (ip("0.0.0.0"))) then (decimal("0.0")) else (decimal("0.0"))) == (decimal("0.0")))) && false
};
