forbid(
  principal == a::"66666666666",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((ip("c3c3:c3c3:c3c3:c3be:c3c3:c3c3:c3c3:c3c3/66")) == (ip("e2e2:e2e2:e2e2:e2e2:ffff:ffff:ffff:ffff"))) then (if true then (ip("ffff:ff12:ffff::fffffff::ffffffff::ffffffff::ffffffff::ffffffff//126")) else (ip("51fff::fffffff::ffffffff::ffffffff::ffff3366::22552255:ffff:ffff/65"))) else (if true then (ip("ffff:ffffff:ffffffff::33222255::2255ffff:fffffff::fffff::Ãf03/126")) else (ip("ffff:ffffff::fffffff::ffffffff::ffffffff::ffffffff::fffffff:ffff/126")))) == (if ((decimal("0.1")) == (decimal("0.203"))) then (if true then (ip("41fff::fffffff::ffffffff::ffffffff::ffffffff::ffff:ffff:12ff/65")) else (ip("22009.0.0.0/11"))) else (ip(""))))) && ((if ((decimal("--33332764857145221.879")) == (decimal("--3332764795407171.5840"))) then (decimal("6")) else (if true then (decimal("--33322776644885577114455222211..887799")) else (decimal("90116835.3745")))) == (decimal("0.0")))) && false
};
