@AjwFp("3\u{1}\0\\\t")
@AjwFrp1000309("")
@AjwFrp1002222("AAA")
@B("6")
@B00333("")
@C("m")
@J30tk333("\0\0")
@J3k00("\0")
@M22222vlmq22222("AAAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAA\06")
@lygbcdxt0000("\0t")
@lygbcdxt003s("")
@r("id")
@rr93("m\0\0\0")
@s("\0-")
permit(
  principal,
  action,
  resource
) when {
  (true && ((decimal("")) == (if true then (decimal("")) else (if true then (decimal("-199648.8449")) else (decimal("0.0")))))) && false
};
