@B("m")
@J("")
@KAAAAAAAAAA("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\u{b}\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n6666\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}\u{3}333333333333333")
@Z("")
@r("333333\n\n\n\n\n\n\n\n\n\n\n333\0\0\0")
@z("3333333333\0\0\0\0\0\0\0Y3")
permit(
  principal,
  action,
  resource is a in a::"\n\n\n\n\n"
) when {
  true
};
