permit(
  principal is a in a::"6",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if false then (decimal("0.1")) else (decimal("0.1")))) == (if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))))) && ((if ([] == []) then (decimal("\0\0666\u{1}\0")) else (if true then (decimal("0.1")) else (decimal("0.1")))) == (if (principal is a) then (decimal("6")) else (decimal(""))))) && (!(r::r::r33333333333::r::Gjs33333::"6666" is a))
};
