@Bsss("63-+++++\u{17}\u{17}\u{17}\u{17}\u{17}\u{17}\u{17}++++++++++++++++++++++++++")
forbid(
  principal is XNNNNNN in XNNNNNN::"",
  action in [Action::"action"],
  resource == XNNNNNN::""
) when {
  (true && (({"\0": decimal("-2195724721k97.6906"), "": action}[""]) in [Action::"action"])) && (true && ((if true then (decimal("-3.2769")) else (decimal("0.239"))) == (if true then (decimal("0.1")) else (decimal("0.1")))))
};
