forbid(
  principal == a::"",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((ip("c3c3:c3c3:c3c3:c3be:c3c3:c3c3:c3c3:c3c3/66")) == (ip("ffff:ffe5:e523:c3:c3c3:c3c3:c3c3:c3c3/126"))) then (if true then (ip("dd1dd11::44114411::44114411::44114411::ffffffff:ffff:ffff:ffff/80")) else (ip("dd11dd1::dd11dd44::dd11dd11::dd11dd11::d1d1:4141:4141:4141/80"))) else (if true then (ip("33bffff::1122ffff::ffffffff::ffffff::fffff::ffffÃf:ffff:ff36/80")) else (ip("4411441::44114411::ffffffff::ffffffff::ffffffff::fffff:ffff:ffff/65")))) == (ip("")))) && ((decimal("")) == (decimal("")))) && ((if ((decimal("-33332277664477994499778899559.33883388")) == (decimal("--332764795055774.847"))) then (if true then (decimal("0.1")) else (decimal("-109951162.7776"))) else (if true then (decimal("0.1")) else (decimal("0.1")))) == (if ((decimal("0.1")) == (decimal("11.5651"))) then (decimal("1434.2874")) else (decimal("0.0"))))
};
