@A("66\n\u{e}id")
@r("\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}")
permit(
  principal in a::"\0\'",
  action == Action::"action",
  resource in a::"\0\'"
) when {
  (true && (((false == false) == (false == false)) == ((false == false) == (false == false)))) && (((false == false) == ((decimal("-26388279066.6241")) == (decimal("0.1")))) == (false == false))
};
