permit(
  principal in a::"\u{1}",
  action == Action::"action",
  resource in a::"\u{1}"
) when {
  (true && ((if (resource has "B_qcssprobsws") then (if false then resource else resource) else (if false then resource else resource)) has "B_qcssprobsws")) && ((if (resource has "B_qcssprobsws") then (if false then resource else resource) else (if false then resource else resource)) has "B_qcssprobsws")
};
