permit(
  principal,
  action in [B::Action::"action"],
  resource
) when {
  ((true && (if (if (if true then true else true) then (if true then false else true) else (if true then true else true)) then (if (if true then true else true) then (if true then true else true) else (if true then true else true)) else (if (if true then true else true) then (principal in principal) else (principal in principal)))) && (action in action)) && (action in action)
};
