@a("")
@hC31("")
@lstRvbszcssssk3D("")
@r("")
permit(
  principal,
  action in [Action::"action",Action::"action",Action::"action"],
  resource
) when {
  ((true && (if (action has "\0\0\0\0\0\0\0\u{8}H333133H6666\0\0\0`\0\0\0") then (a::"" has "\0\0\0\0\0\0\0\u{8}H333133H6666\0\0\0`\0\0\0") else (a::"" has "\0\0\0\0\0\0\0\u{8}H333133H6666\0\0\0`\0\0\0"))) && ((decimal("7205759403792.7935")) == (decimal("0.0")))) && false
};
