@V111("\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}\u{7f}6\0\0\0\0\0\0\0Y6&66\0\0\0\0666666666666vz6.6")
permit(
  principal in a::"vz6\0\0\0",
  action == Action::"action",
  resource == a::"vz6\0\0\0"
) when {
  ((true && (((if false then resource else resource) has "C") == ((if false then resource else resource) has "C"))) && ((if (resource has "C") then a::"vz6\0\0\0" else a::"vz6\0\0\0") has "C")) && ((if ((ip("182.182.182.182")).isIpv4()) then (-4019965459004213578) else 51711) == 0)
};
