@F("n")
forbid(
  principal,
  action in [Action::"\u{2}"],
  resource
) when {
  ((true && ((if (resource in resource) then (if true then resource else resource) else (if true then resource else resource)) == (if (resource in resource) then (if false then principal else resource) else (if true then resource else principal)))) && (IffJfffffffffff::Iffffffffffffff::Ifffffffargmsss::I::"" is p)) && (false == ((decimal("")).greaterThan(decimal("@on"))))
};
