@B("action6")
@J("")
forbid(
  principal,
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("0.1")) == (decimal("-98297708.4929"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("-26270984402.9167")))) == (if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("-130862.2849"))) else (if true then (decimal("122976417324925.3649")) else (decimal("0.1")))))) && (resource in resource)) && ((if (if true then true else true) then (if true then true else true) else (if true then true else true)) == (if true then ((decimal("0.1")) == (decimal("0.1"))) else ((decimal("0.1")) == (decimal("0.1")))))
};
