@B("action6")
@J("")
forbid(
  principal,
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("0.1")) == (decimal("-98297708.4929"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("-26270984402.9167")))) == (if ((decimal("0.1")) == (decimal("0.256"))) then (if true then (decimal("0.1")) else (decimal("-367421.305"))) else (decimal("\u{19}\u{11}\u{11}"))))) && (if ((if true then true else true) == (if true then true else true)) then (resource in resource) else (((decimal("0.1")) == (decimal("129703669268264.7551"))) == ((decimal("0.1")) == (decimal("0.1")))))) && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))) == (if (true == true) then (decimal("\u{19}\u{11}\u{11}")) else (decimal("\u{19}\u{11}\u{11}"))))
};
