permit(
  principal is r::urgmlWamlqrpY::K6s333sFM::r::a in r::urgmlWamlqrpY::K6s333sFM::r::a::"",
  action in [r::urgmlWamlqrpY::K6s333sFM::r::Action::"action"],
  resource is r::urgmlWamlqrpY::K6s333sFM::r::a in r::urgmlWamlqrpY::K6s333sFM::r::a::""
) when {
  (true && (!(6799976246779207262 <= (r::urgmlWamlqrpY::K6s333sFM::r::a::""["zpd8"])))) && (!((if (false == false) then 6799976073397272576 else (principal["zpd8"])) <= 408021893120))
};
