@k66666666("")
@k6X000066("")
@zppppoF0ssssD("")
permit(
  principal == B::a::"",
  action in [B::Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}")) == (decimal("\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}1689.4069"))) then (if true then (decimal("-4340410370\u{8b}46\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}")) else (decimal("-50016999.\u{8b}\u{8b}\u{8b}\u{8b}"))) else (decimal(""))) == (decimal(if true then "" else "")))) && (!(!(!true)))) && (!(!(!true)))
};
