permit(
  principal == fB::Es::fF::a::"tttttttttttttttttttttttttttttttttttttttMMMMMMMMMM6666&6",
  action in [fB::Es::fF::Action::""],
  resource == fB::Es::fF::a::"tttttttttttttttttttttttttttttttttttttttMMMMMMMMMM6666&6"
) when {
  (true && ((ip(principal["B"])).isIpv4())) && (({"tttttttttttttttttttttttttttttttt": decimal("752337797515997.3992")}["tttttttttttttttttttttttttttttttt"]).lessThan({"tttttttttttttttttttttttttttttttt": decimal("-6.5536")}["tttttttttttttttttttttttttttttttt"]))
};
