@ReeKKKKKK("")
@y("\0+Š6")
@yKKKKK("")
@yKKKKs("6666id666>6665\0+")
@yKKKee("")
permit(
  principal,
  action in [r::A0000023333::r::r::r::r::r::r333KKKKKKKKKKKc::yKKKKK::ylKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::y33333::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r333333333::r::r::r::r::r::r::r::Np::r3333ss::Bsss::L::Action::"action",r::A0000023333::r::r::r::r::r::r333KKKKKKKKKKKc::yKKKKK::ylKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::y33333::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r333333333::r::r::r::r::r::r::r::Np::r3333ss::Bsss::L::Action::"action"],
  resource is r::A0000023333::r::r::r::r::r::r333KKKKKKKKKKKc::yKKKKK::ylKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::y33333::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r333333333::r::r::r::r::r::r::r::Np::r3333ss::Bsss::L::B in r::A0000023333::r::r::r::r::r::r333KKKKKKKKKKKc::yKKKKK::ylKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::y33333::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r333333333::r::r::r::r::r::r::r::Np::r3333ss::Bsss::L::B::""
) when {
  true && (action is r::A0000023333::r::r::r::r::r::r333KKKKKKKKKKKc::yKKKKK::ylKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::yKKKKK::y33333::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r333333333::r::r::r::r::r::r::r::Np::r3333ss::Bsss::L::r)
};
