@r("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\0\0\0\0\0\0\06666666666666")
forbid(
  principal == fB::Es::fB::a::"tMMMMMtttttttttttttt{ttttttt",
  action in [fB::Es::fB::Action::""],
  resource
) when {
  ((true && ([[ip("0:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3"), ip("c3c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3/66"), ip("2525:2525:2525:2525:2525:c3c3:c3c3:c3c3/37")], [ip("c3c3:c3c3:c3c3:c3c3:c3c3::c3/66"), ip("54.54.54.54"), ip("0.74.74.74")], [ip("36c2:f2f2:3536:3636:3636:3636:3636:c3c3/66"), ip("6767:67c3:c300::c3c3/122"), ip("::25:2525:2525:2525:257e:2525")]] == [])) && true) && ((if ((ip("::36:36c3")) == (ip("a436:c2f2:f236::3636:3636:3636:364d:4d4d/66"))) then (ip("tttttttttttttt{ttttttttttttttttttttttttttttttu")) else (ip("tttttttttttttt{ttttttttttttttttttttttttttttttu"))) == (ip(if true then "tttttttttttttt{ttttttttttttttttttttttttttttttu" else "tttttttttttttt{ttttttttttttttttttttttttttttttu")))
};
