permit(
  principal is a in a::"6",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if false then (decimal("0.1")) else (decimal("0.1")))) == (decimal(if true then "//////////66666[666" else "")))) && ([].contains(if false then (if false then (-1) else (-1)) else (-1)))) && (a::"6" == (if (if true then true else false) then a::"6" else a::"6"))
};
