forbid(
  principal == B::a::"",
  action in [B::Action::"action"],
  resource
) when {
  (true && ((if ((decimal("\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}3\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}")) == (decimal("\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}9"))) then (decimal("21524555924.985")) else (decimal("0.0"))) == (decimal("0.0")))) && false
};
