@U66666666("")
@k66666666("")
@k6666666r("")
permit(
  principal,
  action in [r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::B::r::Action::"action"],
  resource
) when {
  ((true && ((if ((ip("c367:6767:6767:6767:6767:c3c3:c3c3:c3c3/66")) == (ip("0.255.255.93/24"))) then (resource["k6sssssss"]) else (resource["k6sssssss"])) == (r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::B::r::a::""["k6sssssss"]))) && (false && (false == false))) && ((decimal("")) == (decimal("")))
};
