forbid(
  principal,
  action in [Action::"action"],
  resource
) when {
  ((true && (if ((if true then (-1) else (-1)) == (if true then (-4026531841) else 767)) then true else ((if false then (decimal("0.1")) else (decimal("14468034993743.4623"))) == (decimal("\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}"))))) && (((false == false) == (false == false)) == ((false == false) == (false == false)))) && true
};
