forbid(
  principal in r::r::r::r33333333::r::r::r::r::r::r::Biiiii::Biiiii::Biiiii::r::a::"",
  action == r::r::r::r33333333::r::r::r::r::r::r::Biiiii::Biiiii::Biiiii::r::Action::"action",
  resource in r::r::r::r33333333::r::r::r::r::r::r::Biiiii::Biiiii::Biiiii::r::a::""
) when {
  (true && (r::r::r::r33333333::r::r::r::r::r::r::Biiiii::Biiiii::Biiiii::r::a::""["NmqqA"])) && (r::r::r::r33333333::r::r::r::r::r::r::Biiiii::Biiiii::Biiiii::r::a::""["NmqqA"])
};
