permit(
  principal is a in a::"0",
  action in [Action::"action"],
  resource == a::"0"
) when {
  ((true && ((if ((decimal("0.1")).lessThan(decimal("0.1"))) then (decimal("ef\0\0e\0\0\0")) else (decimal("\u{1}&\0\n\0\t041"))) == (decimal("\0\0")))) && ((if true then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal(".1")))) == (if false then (decimal("")) else (if true then (decimal("0.1")) else (decimal("0.1")))))) && false
};
