forbid(
  principal == r::r::r::r::A3::r::r::r::r::r::r::r::r::r::r::r::r::r::r::a::"",
  action == r::r::r::r::A3::r::r::r::r::r::r::r::r::r::r::r::r::r::r::Action::"action",
  resource is r::r::r::r::A3::r::r::r::r::r::r::r::r::r::r::r::r::r::r::a in r::r::r::r::A3::r::r::r::r::r::r::r::r::r::r::r::r::r::r::a::""
) when {
  true && (r::r::r::r::A3::r::r::r::r::r::r::r::r::r::r::r::r::r::r::a::"" has "")
};
