forbid(
  principal == r::r::r::r::r::Q::r::z::"",
  action in [r::r::r::r::r::Q::r::Action::"action"],
  resource == r::r::r::r::r::Q::r::z::""
) when {
  (true && (if (r::r::r::r::r::Q::r::Action::"action" in r::r::r::r::r::Q::r::Action::"action") then (r::r::r::r::r::Q::r::Action::"action" in r::r::r::r::r::Q::r::Action::"action") else (r::r::r::r::r::Q::r::Action::"action" in r::r::r::r::r::Q::r::Action::"action"))) && (r::r::r::r::r::Q::r::Action::"action" in r::r::r::r::r::Q::r::Action::"action")
};
