permit(
  principal in a::"AAAAAAAA\u{1b}\u{1b}\u{1b}attrs\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}",
  action in [Action::"action",Action::"action",Action::"action"],
  resource in a::"AAAAAAAA\u{1b}\u{1b}\u{1b}attrs\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}"
) when {
  ((true && (true || (true && ("AAAA\n\n\n\n\n\n\n" == "")))) && (((9223372036854775807 * 9223372036854775807) * 9223372036854775807) == 9223372036854775807)) && false
};
