permit(
  principal is r::urgmlWamlqrpY::K6s333sFM::r::a in r::urgmlWamlqrpY::K6s333sFM::r::a::"",
  action in [r::urgmlWamlqrpY::K6s333sFM::r::Action::"action"],
  resource is r::urgmlWamlqrpY::K6s333sFM::r::a in r::urgmlWamlqrpY::K6s333sFM::r::a::""
) when {
  (true && (!((r::urgmlWamlqrpY::K6s333sFM::r::a::""["zpd8"]) <= (r::urgmlWamlqrpY::K6s333sFM::r::a::""["zpd8"])))) && (!((r::urgmlWamlqrpY::K6s333sFM::r::a::""["zpd8"]) <= (r::urgmlWamlqrpY::K6s333sFM::r::a::""["zpd8"])))
};
