forbid(
  principal == a::"63333330",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (-1) else (-1)) else (if false then (-1) else (-1))) == (if ((decimal("0.1")) == (-1)) then (-1) else (if false then (-1) else (-1))))) && ((if ((ip("3333:3276:3333:ca33:aa36:36ff:3636:ff36/50")).isInRange(ip("ff37:a036:6cff:ffff:ff38:3616:f3b6:36ff/126"))) then (ip(">66666\u{17}\u{17}\u{17}")) else (ip(""))).isIpv4())) && false
};
