@A033303333("")
@B("")
@F("")
@HUUUUUUUUUUU3000("\0<6663nnnnnn\u{2}")
@HUUUUUUUUUUUUUUU("")
@r("\0\0\u{2}")
permit(
  principal == a::"66z\u{1}\0\0\0\0\0\0\u{6}v233=233Set\0",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("578721382704613.4015")) == (decimal("578721382704613.3840"))) then (decimal("6.5535")) else (decimal("0.0"))) == (decimal("0.0")))) && false) && false
};
