@k66666666("")
@k6o666X40("")
permit(
  principal,
  action in [B::Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}")) == (decimal("\u{8b}\u{8b}\u{8b}\u{9b}\u{8b}\u{8b}\u{8b}\u{b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}Ã89.4069"))) then (decimal("\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}")) else (decimal("\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}"))) == (decimal("327320.1945")))) && false) && false
};
