@B("")
@J("")
@KAAAAAAAAAA("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n6666666v>\n\n\n\n\n\n\n\n\n\n\n\n")
@KAAAApppppp("333333333B333333")
@KAAAApppsss("")
@Z("")
@r("")
@z("3333333333333333333333333333333333333333\0\0\0\0\0\0\0Y3")
forbid(
  principal is a in a::"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n",
  action in [Action::"action"],
  resource is a in a::""
) when {
  true && (a::"" has "")
};
