@k66601000("")
@k666666p6("")
permit(
  principal,
  action in [B::Action::"action"],
  resource
) when {
  ((true && (((if true then action else action) has "k6sssssss") == ((if true then action else action) has "k6sssssss"))) && ((if (action has "k6sssssss") then (if true then action else action) else (if true then action else action)) has "k6sssssss")) && ((if (action has "k6sssssss") then (if false then principal else principal) else principal) has "k6sssssss")
};
