@B00xs6("")
@gWWWWWWWWCWWWWWW("    ")
@gWWWWWWWWWWWWWWW("       ")
@mssI("\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}66666ef6667\u{1}")
@r("")
permit(
  principal == r::"",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("-188084449378999.3499")) == (decimal("-188084449378999.3499"))) then (decimal("")) else (decimal(""))) == (decimal(if true then "" else "")))) && (Action::"action" in Action::"action")) && (Action::"action" in Action::"action")
};
