@XWamlqrpYglrSSS("[[[[[[[[[[[[[[[[[[[[[[[[[[[")
@Xkkkkkkkkkkkkkk("")
@mSSSSSG("6zppppepo")
forbid(
  principal is a in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource is a in a::"666>66\u{1}\0[[[[["
) when {
  (true && (!(128858986646063727 == (!false)))) && (!(([].containsAny([])) || ((decimal("132714490.6496")).greaterThanOrEqual(decimal("-8900377435730775.6432")))))
};
