@B("action6")
@J("")
forbid(
  principal,
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("0.1")) == (decimal("-98297708.4929"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("-26270984402.9167")))) == (if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("-24079304648.2945"))) else (if false then (decimal("122978293824730.3424")) else (decimal("-6079859496950.1697")))))) && (if ((if true then true else true) || ((decimal("0.1")) == (decimal("0.1")))) then ((if true then (decimal("0.1")) else (decimal("0.1"))) == (if true then (decimal("0.1")) else (decimal("0.1")))) else ((if true then (decimal("0.1")) else (decimal("0.1"))) == (if true then (decimal("122978293824730.3441")) else (decimal("0.1")))))) && ((if (true == true) then (decimal("")) else (decimal(""))) == (decimal(if true then "" else "")))
};
