forbid(
  principal is a in a::"66-3nnnnnn\u{2}",
  action == Action::"action",
  resource == a::""
) when {
  ((true && (resource in a::"")) && ([[true]].contains([if true then (-7161677112663853404) else 7301235715885691446, (-14156032), if true then (-1) else (-11821949021847553)]))) && (if (if (if true then true else true) then true else (if true then false else true)) then false else true)
};
