forbid(
  principal == a::"",
  action in [],
  resource == a::""
) when {
  ((true && ((if ((-51470) == (-1)) then (if true then (decimal("0.1")) else (decimal("390637019993001.1647"))) else (if true then (decimal("0.1")) else (decimal("-7194631052576.5889")))) == (if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("8646976997550.9870")) else (decimal("701699676529343.7281")))))) && ((if ((decimal("-390625561787064.5505")) == (decimal("0.0"))) then (decimal("0.0")) else (decimal("0.0"))) == (decimal("0.0")))) && false
};
