@BsssssF0ssssD("")
@k66666666("")
@k6X000066("")
forbid(
  principal,
  action in [B::Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}")) == (decimal("\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}g89.4069"))) then (if true then (decimal("-43404103702\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}\u{8b}")) else (decimal("-434041037028465.357"))) else (decimal("0.0"))) == (decimal("0.0")))) && false) && false
};
