forbid(
  principal == a::"",
  action in [Action::"action"],
  resource == a::""
) when {
  (true && (if (if (if false then false else false) then (if false then false else false) else (if false then false else true)) then ({"": (-5045959052422678023), "kZRRs6666$\0\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}": []} has "") else (action has ""))) && (action has "")
};
