permit(
  principal == a::"6",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ([].containsAny([])) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))) == (decimal("")))) && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))) == (decimal("0.1")))) && true
};
