@C("\0\0\0\0\0\u{1}\0\0\0\0\0\0\u{1}\0\0")
@C22("\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}\u{2}")
@P("")
@r("")
@r3333("")
permit(
  principal in a::"",
  action == Action::"action",
  resource in a::""
) when {
  (true && (((false == false) == (false == false)) == ((false == false) == (false == false)))) && (((false == false) == ((decimal("-26388279066.6241")) == (decimal("0.1")))) == (false == false))
};
