forbid(
  principal == r::r::r::r::r::r::r::r::r::n::r::Q::r::BsYllmrYr::"",
  action in [r::r::r::r::r::r::r::r::r::n::r::Q::r::Action::"action"],
  resource == r::r::r::r::r::r::r::r::r::n::r::Q::r::C::""
) when {
  (true && (r::r::r::r::r::r::r::r::r::n::r::Q::r::Action::"action" in r::r::r::r::r::r::r::r::r::n::r::Q::r::Action::"action")) && (r::r::r::r::r::r::r::r::r::n::r::Q::r::Action::"action" in r::r::r::r::r::r::r::r::r::n::r::Q::r::Action::"action")
};
