permit(
  principal is a in a::"",
  action in [Action::"action"],
  resource
) when {
  ((true && (true == (5714873654208057167 == 5714873654208057167))) && (if (if (if true then false else false) then (if true then true else true) else (if true then true else true)) then (if (if true then true else true) then (if true then true else true) else (if true then true else true)) else (if (if true then true else true) then (if true then true else true) else (if true then false else true)))) && ([].contains(!false))
};
