permit(
  principal is a in a::"6",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if false then (decimal("0.1")) else (decimal("0.1")))) == (if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))))) && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))) == (if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))))) && ((if ((decimal("0.1")) == (decimal("0ÿ1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (decimal("6"))) == (if ((decimal("0.1")) == (decimal("0.1"))) then (decimal("66666")) else (decimal("6\0\u{1c}\0\0\0\0\0\0666"))))
};
