permit(
  principal is a,
  action == Action::"+++++66",
  resource is a
) when {
  ((true && (({"++++++++++++666666": decimal("-446588198049217.1534"), "g222s": decimal("-1519143ê2959961.134"), "++++++++++++++++++++++\u{15}\u{15}\u{15}\u{15}\u{15}\u{15}\u{15}": principal}["++++++++++++++++++++++\u{15}\u{15}\u{15}\u{15}\u{15}\u{15}\u{15}"]) in principal)) && (principal is a)) && ((if (principal in principal) then [] else [(-271579372060463)]).containsAll(if (resource in []) then (if false then [] else []) else (if true then [] else [])))
};
