permit(
  principal is a in a::"",
  action in [Action::"action"],
  resource == a::""
) when {
  ((true && ((if ((decimal("0.0")) == (decimal("0.0"))) then (if true then (decimal("0.0")) else (decimal("0.0"))) else (if true then (decimal("0.0")) else (decimal("0.0")))) == (if ((decimal("0.0")) == (decimal("0.0"))) then (if true then (decimal("0.0")) else (decimal("0.0"))) else (if true then (decimal("0.0")) else (decimal("0.0")))))) && false) && (a::"" in principal)
};
