@Y3EEE3EEEE("M")
@lb0b("%%%%%%%\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0")
@lbbb("%")
@r000000E0E("MMM\0\0\0\0\0\07/")
permit(
  principal in fB::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::Es::fB::a::"",
  action in [fB::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::Es::fB::Action::""],
  resource
) when {
  ((true && ((if ((decimal("0.1")) == (decimal("0.1"))) then (decimal("tttttttttttttt{tttttttttttttttttttttttttttttt")) else (decimal("tttttttttttttt{tttttttttttttttttttttttttttttt"))) == (decimal("tttttttttttttt{tttttttttttttttttttttttttttttt")))) && ((principal["BSv012opu100"]) in ((principal["BSv012opu100"])["BSv012opu100"]))) && (((action["BSv012opu100"])["BSv012opu100"]) in ((action["BSv012opu100"])["BSv012opu100"]))
};
