@M222("AA")
@M2222ZZZZZZZZZZ("##")
@N("")
@NeeeeKKKK("")
@S("")
@ViiiiRssssssl("6")
@jZ("######################AAAAAAAA")
@lott("6919%%%%%%%%%%%")
@ls33("")
@r("")
@vkktKK("")
@yKKKKK("")
@yKKpKK("Q")
@yKNKKK("")
@yeeeZe("")
@z("")
forbid(
  principal in Viiiii933iiii::n333333stl9bb::V::Bsssssls33aee::"",
  action in [Viiiii933iiii::n333333stl9bb::V::Action::""],
  resource == Viiiii933iiii::n333333stl9bb::V::M22ZZZZZZZZZZZZ::"1685/6"
) when {
  true && (Viiiii933iiii::n333333stl9bb::V::M2222223bbottsv::"" in Viiiii933iiii::n333333stl9bb::V::Action::"")
};
