forbid(
  principal,
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))) == (if ((decimal("0.1")) == (decimal("0..1"))) then (decimal("l_constraint")) else (if true then (decimal("0.1")) else (decimal("0.1")))))) && ((if (principal is a) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))) == (decimal(if true then "/" else "")))) && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))) == (if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (decimal("6"))))
};
