@k66666666("")
permit(
  principal == B::a::"",
  action == B::Action::"action",
  resource == B::a::""
) when {
  ((true && ((if (resource has "k6sssssss") then (if true then action else action) else (if true then action else action)) has "k6sssssss")) && ((if (action has "k6sssssss") then (if true then action else action) else (if true then action else action)) has "k6sssssss")) && ((if (action has "k6sssssss") then (if true then action else action) else (if true then action else action)) has "k6sssssss")
};
