@B("")
@r("")
@r333333203303("")
forbid(
  principal == a::"\0\t\063\u{1}\0\0\t",
  action == Action::"action",
  resource == a::"\0\t\063\u{1}\0\0\t"
) when {
  true && (if (if (if true then true else true) then (if true then true else true) else (if true then true else true)) then (if (if true then true else true) then (if true then true else true) else (if true then true else true)) else false)
};
