permit(
  principal in fB::Es::fB::a::"tMMMMMtttttttttttttt{tttttttttttttttttttttttttttttttMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0",
  action in [fB::Es::fB::Action::""],
  resource in fB::Es::fB::a::"tMMMMMtttttttttttttt{tttttttttttttttttttttttttttttttMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
) when {
  true && (((action["BSv012opu100"])["BSv012opu100"]) in ((action["BSv012opu100"])["BSv012opu100"]))
};
