@Fccccccccssscc("\u{1}\0\0\0\0\0\0\u{1}")
@Fccccccccssscs("6666666>666\06")
permit(
  principal is a in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource is a
) when {
  true && ({"ncipal_constraint\0\0\0\n6>$668": {"ncipal_constraint\0\0\0\n6>$668": "ncipal_constraint\0\0\0\n6>$668"}} == {"ncipal_constraint\0\0\0\n6>$668": {"ncipal_constraint\0\0\0\n6>$668": decimal("3906369333256133ù6447")}})
};
