@xTT("")
@xTs("6666\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\u{e}\u{e}\u{e}\u{e}\u{e}\u{e}\u{e}\u{e}\u{e}\u{e}\u{e}\u{e}\u{e}\u{e}\u{e}\u{e}:\u{e}")
permit(
  principal is a in a::"",
  action in [Action::"\u{2}"],
  resource is a in a::""
) when {
  (true && (if (if (if false then false else false) then (if false then false else false) else (if false then false else false)) then false else false)) && false
};
