forbid(
  principal == a::"",
  action in [Action::"action"],
  resource
) when {
  ((true && ([[ip("c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3"), ip("195.195.54.164/30"), ip("c3c3:36c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3/66")], [ip("c3c3:c3c3:c3c3:c3c3:c3c3::c3c3/66"), ip("c3c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3/66"), ip("c3c3:c3c3:c3c3:c3c:c300::c3c3/66")], if false then [] else []] == (if false then (if false then [] else []) else (if false then [] else [])))) && false) && false
};
