@Bss3("6")
@LZY("")
@gWWWW("                                                                                                                                ")
@gWWWWWW("                                                                                                                     ")
@r("\u{8}\0\0\0\u{5}f\0\u{2}")
permit(
  principal in a::"                                                                   \u{14}                                        dur3333333",
  action == Action::"action",
  resource in a::"                                                                   \u{14}                                        dur3333333"
) when {
  true
};
