permit(
  principal is a in a::"0",
  action in [Action::"action"],
  resource == a::"0"
) when {
  ((true && ((if ((decimal("0.1")).lessThan(decimal("0.1"))) then (decimal("ef\0")) else (if false then (decimal("0.1")) else (decimal("0.1")))) == (decimal("\n\0\t333")))) && ((if ("\'" == "") then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if false then (decimal("0.1")) else (decimal("0.1")))) == (decimal("")))) && (!true)
};
