permit(
  principal is a in a::"6",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if false then (decimal("0.1")) else (decimal("0.1")))) == (if false then (if false then (decimal("0.1")) else (decimal("0.1"))) else (decimal("///"))))) && (({"///////////wmnm//////////////6676&>666332%:666": [], "": false}["///////////wmnm//////////////6676&>666332%:666"]).contains((-1)))) && true
};
