@r("\t")
permit(
  principal in r::r::r::A3sss::h::a::"",
  action in [r::r::r::A3sss::h::Action::"action"],
  resource == r::r::r::A3sss::h::a::"\n"
) when {
  ((true && ((if (4482830085559562806 == 3936206153247045174) then (decimal("")) else (decimal("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"))) == (decimal("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")))) && (action has "")) && (!(!(!false)))
};
