permit(
  principal is a in a::"\0\n\0\0\0\0\0\0\0\0\0\0\0\0\0\0\06",
  action == Action::"action",
  resource
) when {
  ((true && ([[true, true, true], if true then [] else [], [false]].containsAll([[[], [], []], [[], []], []]))) && ((principal is a) == false)) && (((if true then (decimal("0.1")) else (decimal("0.1"))) == (if true then (decimal("0.1")) else (decimal("0.1")))) || ((if true then (decimal("0.1")) else (decimal("0.1"))) == (decimal(""))))
};
