forbid(
  principal in a::"\0",
  action == Action::"action",
  resource in a::"\0"
) when {
  (true && (if (if (if false then false else false) then (if false then false else false) else (if false then false else false)) then (if (if false then false else false) then (if false then false else false) else (if false then false else false)) else (if (if false then false else false) then (if false then false else false) else (if false then false else false)))) && (if false then false else true)
};
