forbid(
  principal == a::"",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((ip("c3c3:c3c3:c3c3:c3be:c3c3:c3c3:c3c3:c3c3/66")) == (ip("c3c3:c3c3:c3c3:c3c3:c3c3::c3/66"))) then (if true then (ip("c3c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3/66")) else (ip("c3c3:c3c3:c3c3:c3c33:c300::c3c3/66"))) else (if true then (ip("c3c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3/66")) else (ip("c3c3:c3c3:c3c3:c3c3::c3:c3c3/66")))) == (if ((ip("c3c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3/66")) == (ip("0.0.0.0"))) then (ip("0.0.0.0")) else (ip("0.0.0.0"))))) && false) && false
};
