permit(
  principal is r::A0000023333::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::V::r::r::r::r::r::r::r::r::r::r::r::Irj33333ss3sssss::r::zp33 in r::A0000023333::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::V::r::r::r::r::r::r::r::r::r::r::r::Irj33333ss3sssss::r::zp33::"",
  action in [r::A0000023333::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::V::r::r::r::r::r::r::r::r::r::r::r::Irj33333ss3sssss::r::Action::"action"],
  resource
) when {
  true
};
