@AjwF222222222("AAA")
@AjwFrp1000309("")
@AjwFrp1002222("")
@B("actitempc")
@J("")
@J30tk333("\0\0")
@J3k00("h\0\0\0\0")
@M22("AAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAA")
@M22222222222222("")
@M222u2222222222("AAAAAAAA\0")
@lygbcdxt003s("")
@r("")
permit(
  principal in a::"",
  action in [Action::"action"],
  resource is a in a::""
) when {
  (true && ((if (false == false) then (decimal("\0\0")) else (decimal("\0\0"))) == (if (resource in principal) then (decimal("922337203685477.5807")) else (decimal("922337203685477.5807"))))) && false
};
