forbid(
  principal is M::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::BcpD::z in M::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::BcpD::z::"",
  action in [M::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::BcpD::Action::"action"],
  resource == M::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::BcpD::z::""
) when {
  true && ((ip(principal["Asssssssxplllll"])).isIpv4())
};
