forbid(
  principal == a::"",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((ip("c3c3:c3c3:c3c3:c3be:c3c3:c3c3:c3c3:c33c3/66")) == (ip("f5ff:f5ff:f563:f536:366f9:f5f9:b9f9:f9ff/1ù6"))) then (if false then (ip("0.0.0.0")) else (ip("ff30:6d6d:6d6d:6d46:3636:362b:3665:3636/126"))) else (if true then (ip("c3c3:c3c3:c3c3:c3c3:c3c3:c300::/66")) else (ip("38c3:c3c3:c3c3:c3c3:c3c3:bec3:c3c3:c3c3/66")))) == (if ((ip("c336:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3/66")) == (ip("195.195.0.0/30"))) then (if true then (ip("c3c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3")) else (ip("6767:6767:6767:c3c3:c3c3:c3c3:c3c3:c3c3/103"))) else (ip("6666\u{16}"))))) && (principal is a)) && ((if ((ip("c3c3:c3c3:c334:3439:317f:0:c3:c3c3/66")) == (ip("195.164.54.1944/30"))) then (if true then (ip("ffff:ffff:ffff:ffc3:c3c3:c3c3:c3c3:c3c3/126")) else (ip("0.0.0.0"))) else (if false then (ip("0.0.0.0")) else (ip("0.0.0.0")))) == (if false then (if false then (ip("0.0.0.0")) else (ip("38:ffff:ffff:ffff:ffff:ffff:ffff:ffff"))) else (if true then (ip("0.0.0.0")) else (ip("0.0.0.0")))))
};
