permit(
  principal is a in a::"6",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))) == (if true then (if true then (decimal("0.1")) else (decimal("0.1"))) else (decimal("1"))))) && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))) == (decimal("")))) && ((if ((-1) == (-1)) then (if true then (-1) else (-1)) else (if true then (-1) else (-1))) == (if (true == true) then (if true then (-1) else (-1)) else (if true then (-1) else (-1))))
};
