permit(
  principal is a in a::"662\u{1}NNNNNNNN66",
  action,
  resource in a::"662\u{1}NNNNNNNN66"
) when {
  ((true && ((if (resource in resource) then (if true then resource else resource) else (if true then resource else resource)) in (if (resource in resource) then (if true then resource else resource) else (if true then resource else resource)))) && ((if (resource in resource) then resource else action) in a::"662\u{1}NNNNNNNN66")) && ((if (principal in principal) then principal else principal) in principal)
};
