@B("66666@")
@UC33pppppnpp233("")
@b7777npCCAC33pp("333133")
@bU77777777777np("")
@m("")
@nJJ77U7777("")
@nJJJJJJJJJ("")
@nJJJJJJJpJ("")
@nJJJJOJJJJ("")
@nOJJJJJJSJ("")
@r("")
@zYar("ion_co\u{11}\u{11}\u{11}\u{11}\u{11}\u{11}\u{11}\u{11}\u{11}\0\0")
forbid(
  principal,
  action in [Action::"action"],
  resource == z::""
) when {
  ((true && ([if true then true else true].contains(if (if true then true else true) then (if true then true else true) else (if true then true else true)))) && (if false then false else true)) && (true && ("" == "666666@6"))
};
