permit(
  principal,
  action,
  resource
) when {
  (true && ((if (!(648553668691370016 < (-2368858081646862296))) then (if false then resource else resource) else (if false then resource else resource)) is a)) && (!(({"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0": false, "                                             ": 5989822688774848512}["                                             "]) < (-6004244624916130989)))
};
