forbid(
  principal == a::"",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((ip("c3c3:c3c3::1:c3c3:c3c3/66")) == (ip("c3c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3/66"))) then (if false then (ip("3605:1c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3")) else (ip("c2f2:f236:3636:3636:3636:3636:36c3:c3c3"))) else (ip("1944"))) == (if ((ip("c3c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3:c3c3/66")) == (ip("::c3:c3c3:c3c3:c3c3:c3c3:c3c3/66"))) then (if true then (ip("c3c3:c3c3:3434:3931:7f00:0:c3c3:c3c3/66")) else (ip("daff:ffff:ffff:ffff:ffff:ffff:ffff:ffff"))) else (ip("0.0.0.0"))))) && false) && false
};
