permit(
  principal,
  action in [Action::"action"],
  resource
) when {
  ((true && (((if true then (decimal("-7205759401779.5124")) else (decimal("-7205759401779.5124"))) == (decimal("\u{10d34d}"))) == (if (if true then true else true) then (if true then true else true) else (if true then true else true)))) && (true == (true == ((decimal("-7205759401779.5124")) == (decimal("-7205759401779.5124")))))) && false
};
