permit(
  principal is a in a::"6",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (decimal("ction\0\0\0\0\0\0\0\u{8}"))) == (if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))))) && ((if ((decimal("0.1")) == (decimal("0.1"))) then (decimal("66\u{1}\0")) else (if true then (decimal("0.1")) else (decimal("0.1")))) == (if (principal is a) then (decimal("6")) else (decimal(""))))) && (!(Gjss3sss::"" is a))
};
