forbid(
  principal == r::r::r::r::r::r::r::r::r::r::r::Q::r::r::"",
  action in [r::r::r::r::r::r::r::r::r::r::r::Q::r::Action::"action"],
  resource == r::r::r::r::r::r::r::r::r::r::r::Q::r::r::""
) when {
  (true && (r::r::r::r::r::r::r::r::r::r::r::Q::r::Action::"action" in r::r::r::r::r::r::r::r::r::r::r::Q::r::Action::"action")) && (r::r::r::r::r::r::r::r::r::r::r::Q::r::Action::"action" in r::r::r::r::r::r::r::r::r::r::r::Q::r::Action::"action")
};
