permit(
  principal is r::y333sFM::G::r::r in r::y333sFM::G::r::r::"\u{1}\0\0/3335v6z6",
  action in [r::y333sFM::G::r::Action::"66"],
  resource in r::y333sFM::G::r::r::"\u{1}\0\0/3335v6z6"
) when {
  ((true && ((((ip("255.91.54.54/21")).isIpv4()) || ((ip("54.211.51.204")).isIpv4())) || false)) && (((ip("66[")).isIpv4()) || (((ip("d333:d236:3636:3636:3636:3636:3600:3648")).isIpv4()) == ((ip("54.54.54.54")).isIpv4())))) && ((if ((ip("54.0.54.63")).isIpv4()) then false else ((ip("54.54.62.54")).isIpv4())) == ((ip("66")).isIpv4()))
};
