permit(
  principal is r100Ass3ssIsst77 in r::"",
  action in [Action::"action"],
  resource
) when {
  ((true && (((ip("")).isIpv4()) == ((decimal("3\u{1}\0\0\0\n66")).greaterThanOrEqual(if false then (decimal("50638141681658.8342")) else (decimal("389736213309542.9942")))))) && ((if ((decimal("390636933325614.543")) == (decimal("397842731384117.6374"))) then (decimal("")) else (decimal(""))) == (decimal(action["A000Ass3ssssst777"])))) && false
};
