forbid(
  principal,
  action,
  resource
) when {
  ((true && ((decimal("")) == (if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if false then (decimal("0.1")) else (decimal("0.1")))))) && (if (if (if true then true else true) then (if true then true else true) else (if true then true else true)) then (if (if true then true else true) then true else (if true then true else true)) else (if ((decimal("0.1")) == (decimal("0.1"))) then ((decimal("0.1")) == (decimal("0.1"))) else false))) && false
};
