@Cglh("")
permit(
  principal,
  action,
  resource
) when {
  true && {"AgYhhhhRhhhxqZ": {"r": {"A": principal, "AgYhhhhRhhhxqZ": 7667978729021836394, "vw30002333333": a::"\0\0\0\0\0\0\0", "r": "jjj"}, "A": principal}, "A": principal, "r": {"vw30002333333": !a::"\0\0\0\0\0\0\0", "r": context, "A": AhRhh::"z" == a::"\0\0\0\0\0\0\0", "AgYhhhhRhhhxqZ": v0730O000y3hN::""}, "vw30002333333": a::"\0\0\0\0\0\0\0"}
};
