permit(
  principal in r::a::"",
  action == r::Action::"action",
  resource in r::a::""
) when {
  (true && ((("RRRRRRRRRRRRRRRRRRRRRRRRRRRR" == r::a::"RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR") == r::Action::"action") == (("RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR" == r::a::"RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR") == r::Action::"action"))) && ((("RRRRRRRRRRRRRRRRRRRRRRRR" == "RRRRRRR") == ("RRRRRRRRRRRRRRRRRRRRRRRjjj&j" == false)) == r::a::"")
};
