permit(
  principal == a::"jjjj",
  action in [Action::"",Action::""],
  resource == a::"jjjj"
) when {
  ((true && (([Action::"", a::"jjjj"].containsAny([a::"jjjj", Action::"ef", a::"jjjj", yqap0O0000000::"\0\0\0\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}", 9223372036854775807, Action::""])) == 9223372036854775807)) && A::os0N373FY6khZYO::"\u{8}jcjag4") && true
};
