permit(
  principal,
  action in [Tgggggggggg::Tgggggggggg::Tgggggggggg::Tgggggggggg::Tgggggggggg::Tgggggggggg::Tgggggggggg::Tga33hhXhhh::T::Action::"action",Tgggggggggg::Tgggggggggg::Tgggggggggg::Tgggggggggg::Tgggggggggg::Tgggggggggg::Tgggggggggg::Tga33hhXhhh::T::Action::"action",Tgggggggggg::Tgggggggggg::Tgggggggggg::Tgggggggggg::Tgggggggggg::Tgggggggggg::Tgggggggggg::Tga33hhXhhh::T::Action::"action"],
  resource
) when {
  true
};
