permit(
  principal in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource in a::""
) when {
  ((true && ((("        ! 1     \u{1}       ;   1    " == "        ! 1     \u{1}       ;   1    ") == ("        ! 1     \u{1}       ;   1    " == "        ! 1     \u{1}       ;   1    ")) == (("        ! 1     \u{1}       ;   1    " == "        ! 1     \u{1}       ;   1    ") == ("        ! 1     \u{1}       ;   1    " == "        ! 1     \u{1}       ;   1    ")))) && (((false == Action::"action") == (!7165919078637728511)) == a::"")) && principal
};
