@gWWWWWWWWWWWWWWW("       ")
forbid(
  principal in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource in a::""
) when {
  ((true && ((("" == "") == ("" == "")) == (("" == "") == ("" == "")))) && ((("   " == a::"") == (principal == principal)) == jwww000000::k1wwwwwwwwwww::"\u{b}")) && ((("              " == a::"") == (principal == principal)) == ((principal == principal) == (action == false)))
};
