permit(
  principal == a::"\0\"\"\"\"\"\"\"YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"",
  action in [Action::"action",Action::"action"],
  resource is a in a::"\0\"\"\"\"\"\"\"YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY\"\"\"\"\"\"\"\"\"\"\"\"\"\"\""
) when {
  (true && (!((!((5353207850374949482 + 5353172790017673802) < (1207582841260696["_hhh"]))) < a::"\0\"\"\"\"\"\"\"YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY\"\"\"\"\"\"\"\"\"\"\"\"\"\"\""))) && principal
};
