@Ewwwwwwww000("\0")
@jwwww33333("")
forbid(
  principal in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource in a::""
) when {
  ((true && ((("                        " == "                        ") == ("                        " == "                        ")) == (("                        " == "                        ") == "                        "))) && ((("                        " == principal) == (context == 254983214196711)) == principal)) && principal
};
