permit(
  principal,
  action in [Action::"action",Action::"action"],
  resource is a in a::"\0"
) when {
  (true && (if (["DA;`;;;;;;j", a::"", (-1229782938247303442), 7667942410768355310, Aq000::"\0\0\0", 7668058889995087598, Ahvhh::"j*jjh"] == [AhhhA::"", 8389765630838894117]) then ((principal == principal) == (principal == principal)) else ((principal == principal) == (principal == a::"")))) && a::""
};
