permit(
  principal in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource in a::""
) when {
  ((true && (((a::"&[\u{14}\u{13}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{13}" == context) == (mhhh0::"\0" in "$")) == (!({"jj`jjjjNNN": "jj`jjjjNNN"}["V"])))) && ((({"jj`jjjjNNN": "jj`jjjjNNN"}["V"])["V"])["V"])) && ((({"jj`jjjjNNN": "jj`jjjjNNN"}["V"])["V"])["V"])
};
