permit(
  principal == a::"",
  action in [Action::"action"],
  resource in a::""
) when {
  ((true && (a::"ccc" == ([principal, action, Agggh::"j\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0jjhjjjjjj", Ehhhh::"hj\0\0\u{2}kk\0K\\ccccc"].contains(action.contains(Alhhh::"jhj\0\0\u{2}kk\0K\\ccccc"))))) && ([Ahggg::"jj\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", action].contains([Whhlh::"jjjhj\0\0\u{2}kk\0K\\ccccc", action.contains(Agggh::"j")]))) && a::""
};
