permit(
  principal,
  action in [A::k::Action::"action",A::k::Action::"action",A::k::Action::"action"],
  resource in A::k::a::"\u{14}\u{13}"
) when {
  ((true && (((A::k::a::"\u{14}\u{13}" == A::k::a::"\u{14}\u{13}") == (principal == A::k::a::"\u{14}\u{13}")) == ((A::k::a::"\u{14}\u{13}" == A::k::a::"\u{14}\u{13}") == (A::k::a::"\u{14}\u{13}" == A::k::a::"\u{14}\u{13}")))) && (((principal == A::k::a::"\u{14}\u{13}") == (A::k::a::"\u{14}\u{13}" == A::k::a::"\u{14}\u{13}")) == ((A::k::a::"\u{14}\u{13}" == A::k::a::"\u{14}\u{13}") == (A::k::Action::"action" == A::k::a::"\u{14}\u{13}")))) && (((A::k::a::"\u{14}\u{13}" == A::k::a::"\u{14}\u{13}") == (A::k::a::"\u{14}\u{13}" == principal)) == principal)
};
