permit(
  principal is a in a::"\0\0\u{1}\0\0\u{10}\u{10}\u{10}\u{10}\u{10}\u{10}\0\0\0z\u{10}\u{10}\u{10}\u{10}\u{10}\u{10}\u{10}\u{10}\u{10}\u{10}\u{10}\u{10}\u{10}\u{10}\u{10}\u{10}\u{10}\u{10}\u{10}\u{10}\u{10}",
  action in [Action::"action"],
  resource
) when {
  ((true && [[principal, principal, principal, principal, principal, principal, principal] == principal, principal, principal, principal, principal, principal, principal]) && principal) && principal
};
