forbid(
  principal is a in a::"\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}iiijjj",
  action in [Action::"action",Action::"action",Action::"action"],
  resource is a in a::"\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}3\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}\u{13}"
) when {
  ((true && (((1170956875744875283 in context) in (!a::"\u{13}\u{13}\u{13}")) in ("" == Action::"action"))) && Action::"action") && principal
};
