@AhhY("")
@J2g33("\u{19}j")
@K("\n\n\n")
@L("")
@LYX("")
@LYY("")
@T___________("}}}}}}}}}}}}}}}}}}}}}}}}}}")
@V("\0")
@_LL("")
@pLLLAAAacgAh("jjjbjjjjsAgg")
@phhhYAhhhhhh("jjjj\njjjjjjjjj")
@r("")
permit(
  principal == a::"jj\0\0\0",
  action in [Action::"action"],
  resource == a::"jj\0\0\0"
) when {
  ((true && (a::"ccc" == (((-7819937807129209336) * (-7812738666512280685)).contains(a::"jj\0\0\0" == false)))) && false) && Action::"action"
};
