permit(
  principal in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource in a::""
) when {
  ((true && (((a::"" == a::"") == (7667952763424893602 == Atohh::")\0")) == ((a::"" == action) == Ach10::"\u{4}\u{6}ix~\0\0\0\0\0\u{13}"))) && [action, action.isMulticast(), Ach11::"\u{4}\u{6}ix~\0\0\0\0\0\u{13}", [action, a::"".greaterThan(Action::"action"), a::"" in a::"", context, a::"" == a::""], (a::"" == a::"") == (Action::"action" == true)]) && true
};
