@AfhhMFMMMMM("\u{16}\u{16}\u{16}\u{16}\u{16}\u{16}\u{16}\u{16}\u{16}\u{16}")
@WMMMMM("\u{16}\u{16}")
permit(
  principal == wIII::r::w::wIII::wIII::wIII::wIII::wIII::wIII::wIII::wIII::wIII::wIII::wIII::wIII::wIII::wI33::r::r::s::r::K::wIII::a::"j}",
  action in [wIII::r::w::wIII::wIII::wIII::wIII::wIII::wIII::wIII::wIII::wIII::wIII::wIII::wIII::wIII::wI33::r::r::s::r::K::wIII::Action::"action"],
  resource
) when {
  true
};
