@AYg("jjj")
@AhhY("")
@Aq2("ggjjji")
@J9QQN("jji")
@K("\n\n\n")
@L("")
@LYX("")
@LYY("")
@V("\0")
@Z("j")
@_LL("")
@pLLhhhgAhhhh("jjjjjj\njjjjjjjjj")
@r("jsAgg")
permit(
  principal == a::"jj\0\0\0",
  action in [Action::"action"],
  resource in a::"jj\0\0\0"
) when {
  ((true && (a::"ccc" == ((8753308821594215944 * (-2314885970623104647)).contains(a::"")))) && (((true == true) == (!true)) == a::"")) && (((a::"" == a::"") == (a::"" == a::"")) == ((a::"" == a::"") == (a::"" == Ahhhh::AhhhhShh::"jjj\u{14}\u{14}")))
};
