permit(
  principal in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource in a::""
) when {
  ((true && (((a::"" == a::"") == (a::"" == a::"")) == ((a::"" == a::"") == (a::"" == a::"")))) && ((a::"" == (Action::"action" in bfohK::"jjj")) == ((Action::"action" == Action::"action") has "\u{f38e}"))) && (((Action::"action" == Action::"action") == (Action::"action" == Action::"action")) == ((Action::"action" == Action::"action") == (Action::"action" == Action::"action")))
};
