permit(
  principal == a::"\0\0\0",
  action in [Action::"action"],
  resource in a::"\0\0\0"
) when {
  ((true && ([true, resource, [principal, principal, principal, context, principal, action, false], pN000Ovh::Ahhrc::"jjjjjte", a::"\0\0\0" == context, context || context, context || context] == ((context || context) || (context || context)))) && (((context || context) || (context || action)) || ((context || context) == (context || context)))) && ([action, principal, principal, principal, principal, principal, principal] == principal)
};
