permit(
  principal == a::"\0\0\0",
  action in [Action::"action"],
  resource in a::"\0\0\0"
) when {
  ((true && ([true, resource, [principal, principal, principal, context, principal, action, false], ANL00Ovhjhhh::Ahhrc::"", context, context || context, principal || principal] == ((principal == principal) == (principal == principal)))) && (((principal == principal) == (principal == principal)) == ((principal == context) == (context || context)))) && (((context || context) || (context || context)) || ((context || context) || (context || action)))
};
