@c8h8("j")
forbid(
  principal is a in a::"",
  action in [Action::"action"],
  resource is a in a::""
) when {
  (true && [action, ("" in "") in (Av8hxNw_88888888::"" in ""), [resource, "" in "", "" in "", "j" in "", "" in "", "" in "j"], [], ["", "" in "", "" in "\u{1}i", "" in "", "" in a::"", ["", "", "", "", "", ""]], [false, "j", "", "", "", ""] in (Av8h8h8888888888::"" in "")]) && [resource, ("" in "") in ("" in "j"), ["" in "", "" in "", [false, "j", "", "", a::"", A88888888888888h::"jx"], ["", "", "", "", "", "j"], [], [(-8753160913407277443), ""]], [false, resource, "", "", (-8753160913416093696), "j"] in ["", "", "", "", "", ""], [action, "" in "", "" in "", a::"" in "", "" in "", "" in A88888888888888h::"jx"], ["", "" in "", Av8h8h8888888888::"" in "", [false, principal, principal, principal, principal, principal], principal, principal]]
};
