forbid(
  principal is a in a::"",
  action in [Action::"action"],
  resource is a in a::""
) when {
  ((true && (![["", "", resource, "", "jjx", "j"], ["", "", "", "", "", "jx"], ["", "", "", "", "", ""], Av20088888888888::"" in "", ["", "", "", "", "", ""], "" in ""])) && ((("" in false) in ["", "", "", "", "", ""]) in ("" in []))) && ["", ("&jj\0@\0\0" in a::"") in [principal, principal, principal, principal, principal], principal, principal, principal, principal]
};
