@A("")
@AD1("ggjjji")
@AhAA("\n")
@AhhhS("ji\njidjj")
@Aq2("ggjjji")
@K("\n\n\n")
@L("")
@LAA("\n\n\u{2}\0\n\n\n\n\n\n\n\n\n\n")
@LYH("")
@LYY("")
@LYc("")
@Lhh("")
@UKLL("")
@V("\0")
@V00("\0")
@V80("\0")
@Z("j")
@_LL("")
@_hh("j")
@pL00000000LL("")
@pLLLLLLLLLLL("")
@pLLLLLLLLmLLLLLL("")
@pLLLLLZfZZ33("j)jjjjj[jj]jjjjjj&jjj\u{14}\u{14}")
@pLLLTLLLLLLL("")
@r("#)##")
@r33333333333("")
@rh3PAAAAY010Y3YYY("")
permit(
  principal == a::"",
  action in [Action::"action",Action::"action"],
  resource in a::""
) when {
  (true && shh3b::"") && true
};
