forbid(
  principal,
  action in [R::th::R::Action::"action"],
  resource
) when {
  ((true && (R::th::R::a::"j\u{11}\u{11}\u{11}\u{11}jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj2jjj\0\0" in [R::th::R::a::"j\u{11}\u{11}\u{11}\u{11}jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj2jjj\0\0", R::th::R::Action::"action", principal, action, Ahhhh::"k\0", R::th::R::a::"j\u{11}\u{11}\u{11}\u{11}jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj2jjj\0\0", Ahhhh::"jjjjjjjkjjj2jjj\0\0\0"])) && (!"")) && (6884879029837501203 in R::th::R::a::"j\u{11}\u{11}\u{11}\u{11}jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj2jjj\0\0")
};
