@c8h8("j")
forbid(
  principal is a in a::"",
  action in [Action::"action"],
  resource is a in a::""
) when {
  (true && [action, ("" in "") in (Av8h8h8888888888::"" in ""), [resource, "" in "", "" in "", "j" in "", "" in "", "" in "j"], [], ["", "" in "", "" in "\u{1}i", "" in "", "" in a::"", ["", "", "", "", "", ""]], [false, "j", "", "", "", ""] in (Av8h8h8888888888::"" in "")]) && [resource, ("" in "") in ("" in "j"), ["" in "", "" in "", [false, "", "", "", "", ""], "" in false, "" in "", "" in false], principal, principal, principal]
};
