@AhhY("")
@J2g33("\u{19}j")
@K("\n\n\n")
@L("")
@LYX("")
@LYY("")
@T___________("}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}")
@V("\0")
@_LL("")
@pLLL00000000("")
@pLLLLLLLLLLL("\n\n\ncei\njjjjbjjjjsAgg")
@phhhYAhhhhhh("jjjj\njjjjjjjjj")
permit(
  principal == a::"jj\0\0\0",
  action in [Action::"action"],
  resource in a::"jj\0\0\0"
) when {
  ((true && (a::"ccc" == ((8753308821594215944 * (-2314885970623104647)).contains(a::"")))) && (((true == true) == (!true)) == a::"")) && (((a::"" == a::"") == (a::"" == a::"")) == ((a::"" == a::"") == (a::"" == a::"")))
};
