@AYB("jjj")
@Aq2("ggjjji")
@H3("")
@K("\n\n\n")
@L("\0\0 ")
@LML("")
@LfY("")
@M33u3333333("")
@V("\0")
@Z("j")
@ZPPPPPPPP("\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}")
@_("i")
@_hh("j")
@p("))))))))))))))))))))))))))j\njjjjjjjjj")
@pLLLhhhgAhhh("jjjjjj\niii")
@pmjAAAAAAAAA("\ncei\njjjjbjjjjsAgg")
@q("\n\n\n")
@r("")
@r3u13053173("")
@sEEEEEEEEEEEEEEEE("")
@sEEEEEEEYYhq2eehh("ji")
@tVVVVVVVVVVVVVVV("")
@zVVV0("")
@zVVVV("\n")
@zaYVV("")
permit(
  principal == a::"\0\0",
  action in [Action::"action"],
  resource in a::"\0\0"
) when {
  ((true && (a::"ccc" == ((8753308821594215944 * 8753160913407277433).contains(8753160913407277433)))) && 723402782517328249) && true
};
