forbid(
  principal is nddddd::A::nddddd::nddddd::nddddd::nddddd::n20hk::nddddd::a in nddddd::A::nddddd::nddddd::nddddd::nddddd::n20hk::nddddd::a::"",
  action in [nddddd::A::nddddd::nddddd::nddddd::nddddd::n20hk::nddddd::Action::"action"],
  resource is nddddd::A::nddddd::nddddd::nddddd::nddddd::n20hk::nddddd::a in nddddd::A::nddddd::nddddd::nddddd::nddddd::n20hk::nddddd::a::""
) when {
  true && (!((!((!("" < "")) < (!("" < "")))) < (!(("" has "") < (!("" < ""))))))
};
