forbid(
  principal is _h1h in _h1h::"j",
  action in [Action::"action"],
  resource is _h1h in _h1h::"j"
) when {
  (true && (((Action::"action" in Action::"action") in (Action::"action" in Action::"action")) in ((Action::"action" in Action::"action") in (Action::"action" in Action::"action")))) && [(Action::"action" in Action::"action") in (Action::"action" in Action::"action"), (Action::"action" in Action::"action") in (9223372036854775807 in 9223372036854775807), (Action::"action" in Action::"action") in (Action::"action" in Action::"action"), (Action::"action" in Action::"action") < (Action::"action" in Action::"action"), [Action::"action", Action::"action", Action::"action", Action::"action", Action::"action", Action::"action"] in (Action::"action" in Action::"action"), (9223372036854775807 == Action::"action") == (Action::"action" in false)]
};
