@A(")jjjhjjjjjj")
@AYg("jjj")
@Aq2("ggjjji")
@K("\n\n\n")
@L("")
@LAg("\n\n\u{2}\0\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\ncei\njjjjbjjj\n\n\n")
@LYX("")
@LYY("")
@LYc("")
@Lhh("")
@V("\0")
@V00("\0")
@Z("j")
@_LL("")
@pLLLL0YYYYYY("")
@pLLLLLLLLLLL("")
@pLLLLLLLLZfZ("#")
@r("ijj\n\n\n")
permit(
  principal == a::"~^^^jjjj\0\0\0",
  action in [Action::"action"],
  resource in a::"~^^^jjjj\0\0\0"
) when {
  ((true && (a::"ccc" == ((7740160994850794089 * 7740160994850794089) || (!r33h00o00::"\0\0\0\0\0\0\'jj777")))) && (if context then true else true)) && false
};
