forbid(
  principal in r::r::r::r::r333333333::r::r::r::r::A::r::a::"",
  action == r::r::r::r::r333333333::r::r::r::r::A::r::Action::"action",
  resource in r::r::r::r::r333333333::r::r::r::r::A::r::a::""
) when {
  (true && (((r::r::r::r::r333333333::r::r::r::r::A::r::Action::"action" == r::r::r::r::r333333333::r::r::r::r::A::r::Action::"action") == (r::r::r::r::r333333333::r::r::r::r::A::r::Action::"action" == r::r::r::r::r333333333::r::r::r::r::A::r::Action::"action")) == ((r::r::r::r::r333333333::r::r::r::r::A::r::Action::"action" == r::Ahbn3::"") == principal))) && principal
};
