@Ahh3("")
@Aq2("i")
@K("\n\n\n")
@L("")
@LYX("")
@LYY("")
@U("")
@V("\0")
@Z("j")
@_LL("")
@pAAAacgAhhhh("bjjjjsAgg")
@pLLLLLLLLLLL("")
@pLLLLLLQLLLL("")
@pLLLoLLLLLLL("")
@pLLhhhYAhhhh("jjjjjj\njjjjjjjjj")
permit(
  principal == a::"jj\0\0\0",
  action in [Action::"action"],
  resource in a::"jj\0\0\0"
) when {
  ((true && (a::"ccc" == ((8753308821594215944 * (-2318263670343632519)).contains(!a::"")))) && (!(!a::""))) && (((a::"" == a::"") == (a::"" == a::"")) == ((a::"" == a::"") == (a::"" == a::"")))
};
