@A("\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\nv")
@A0("\u{5}")
@AhhYYhq("Aggjjji")
@H3("")
@K("\0\0\0\0\0\0\0\u{3}")
@L("\0\0 ")
@LYX("")
@LYY("")
@LfY("")
@V("\0")
@Z("j")
@ZPPPPPPPP("\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}\u{19}")
@_("i")
@_LL("")
@_hh("j")
@h("")
@p(")))))))))))))))))")
@pLLhhhgAhhhh("jjjjj\niii")
@pffffffh("\njjjjjjjjj")
@pmjAAAAAAAAA("\ncei\njjjjbjjjjsAgg")
@q("\n\n\n")
@r("")
@r3u13053173("")
@sEEEEEEEEEEEEEEEE("")
@sEEEEEEEYYhq2eehh("ji")
@tVVVVVVVVVVVVVVV("")
@zVVV0("")
@zVVVV("\n")
@zaYVV("")
permit(
  principal == a::"\0\0",
  action in [Action::"action"],
  resource in a::"\0\0"
) when {
  ((true && (a::"ccc" == ((8753160913406301704 * 8753038869864741241).contains(true)))) && true) && true
};
