@A000E("VMMM0MMMMMMMJj?i\njjopjj")
@Ahhhh("")
@c8Y9Shm20hBhhh03("\0j\0\0\0\0\0\0\0\0\0MMMMMMM\0\0\0\0MMMMMMMMMMMMJj?i\njjopjj")
permit(
  principal == a::"\0\0\0\0\0$mpljz",
  action in [Action::""],
  resource == a::"\0\0\0\0\0$mpljz"
) when {
  (true && principal) && ((("" == "") == (A::"" == "")) == (("" == "") == (_Ahhmnhhbhhhh::"jjj0A\0jJjjjJAjO\0\0\0\0\0MMMMMMMMMMMMJj?i\njjopjj" == Ahhhh::"0A\0jJjjj\0")))
};
