permit(
  principal == Ageph::a::"",
  action,
  resource
) when {
  ((true && (((Ageph::Action::"action" == Ageph::Action::"action") == (Ageph::Action::"action" == Ageph::Action::"action")) == ((Ageph::Action::"action" == Ageph::Action::"action") == (Ageph::Action::"action" == Ageph::Action::"action")))) && (((Ageph::Action::"action" == Ageph::Action::"action") == (Ageph::Action::"action" == Ageph::Action::"action")) == ((Ageph::Action::"action" == Ageph::Action::"action") == (Ageph::Action::"action" == Ageph::Action::"action")))) && principal
};
