@AYB("jjj")
@Aq2("ggjjji")
@B("\0\0\u{5}")
@H3("")
@K("\n\n\n")
@L("\0\0 ")
@LYY("")
@LfY("")
@V("\0")
@Z("j")
@_("i")
@_LL("")
@_hh("j")
@p(")))))))")
@pLLhhhgAhhhh("jjjjj\niii")
@pmjAAAAAAAAA("\ncei\njjjjbjjjjsAgg")
@q("\n\n\n")
@r(")))))))))))))))))))))))))))j\njjjjjjjjj")
@r3u13053173("")
@r3u33333333("")
@tVVVVVVVVVVVVVVV("")
@zVVV0("")
@zVVVV("\n")
@zaYVV("")
permit(
  principal == a::"\0\0",
  action in [Action::"action"],
  resource in a::"\0\0"
) when {
  ((true && (a::"ccc" == ((8753308821594215944 * 8753160913407277433).contains(8753160913407277433)))) && 723402782517328249) && true
};
