@A00000("###\u{1}\0\0\0\0\0\0\0")
@Acddchrz("jtjj[@jjj")
@H3("ZZi\n0ZZZZ\u{16}")
@Maf66("\u{6}\u{6}\u{6}\u{6}\u{6}ty########\u{1}\0\0\0\0\0\0\0")
@_("i")
@r("gjAch\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}")
@r3u10050000("\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0")
@r3u13053_63("")
@r3u13053_6Y("nnotationsjjjjjiiZZi\n0ZZZZ\u{16}ZZZZZZ")
permit(
  principal,
  action,
  resource == a::"jj"
) when {
  (true && (if _mlqhhhhhggRRgA::sllmr::"ZZZZ\u{16}ZZZZZZ" then a::"[@jjj" else lRRMRR::"Z")) && Action::"action"
};
