@c8h8("j")
forbid(
  principal is a in a::"",
  action in [Action::"action"],
  resource is a in a::""
) when {
  (true && [action, ("" in "") in (Av8hxNw_88888888::"" in ""), [resource, "" in "", "" in "", "j" in "", "" in "", "" in "j"], [], ["", "" in "", "" in "\u{1}i", "" in "", "" in a::"", ["", "", "", "", "", ""]], [false, "j", "", "", "", ""] in (Av8h8h8888888888::"" in "")]) && [resource, ("" in "") in ("" in ""), c888888888888h8h::"", ["", "" in "", "" in "", "" in Av8h8h8888888888::"j", [], [Action::"action", ""]], ("" in "") in (Av20088888888888::"" in ""), ["", "" in "", "" in "j", [Av20088888888888::"", "", A888000000000000::"", principal, principal, principal], principal, principal]]
};
