@APhhh("")
@o("\0jjjjj2rj(j\0\0\u{2}jjjj")
permit(
  principal == a::"esj",
  action in [Action::"action"],
  resource == a::""
) when {
  ((true && (a::"ccc" == ((2882302855420220936 * 2821266740684990247) || (Action::"action" has "\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\')\n\niiijjjj")))) && a::"\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\'\n\niiijjjj") && (Ak222::"" == ((a::"esj" in "") in (a::"esj" in a::"esj")))
};
