permit(
  principal is r::r::r::r::r::r::r::r::r3333::r::c::r::r::r::r::r::r::r3333::r::r::c::r::r::r::r::r::r::r::r::r::r::r::r::r::a in r::r::r::r::r::r::r::r::r3333::r::c::r::r::r::r::r::r::r3333::r::r::c::r::r::r::r::r::r::r::r::r::r::r::r::r::a::"\u{10}\0\u{f}\0",
  action in [r::r::r::r::r::r::r::r::r3333::r::c::r::r::r::r::r::r::r3333::r::r::c::r::r::r::r::r::r::r::r::r::r::r::r::r::Action::"action"],
  resource == r::r::r::r::r::r::r::r::r3333::r::c::r::r::r::r::r::r::r3333::r::r::c::r::r::r::r::r::r::r::r::r::r::r::r::r::a::"\u{10}\0\u{f}\0"
) when {
  true && (!context)
};
