permit(
  principal in a::"",
  action in [Action::"action",Action::"action",Action::"action"],
  resource in a::""
) when {
  ((true && (((a::"" == a::"") == (a::"" == a::"")) == ((a::"" == a::"") == (a::"" == a::"")))) && ((Action::"action" == (Action::"action" == Action::"action")) == ((Action::"action" == Action::"action") == (Action::"action" == Action::"action")))) && (((Action::"action" == Action::"action") == (a::"DDjjj" == Action::"action")) == ((false == Action::"action") == Ah000::"\0\0\0\u{8}\0\0hj\0\0\u{2}ij\0j\0"))
};
