@c8h8("j")
forbid(
  principal is a in a::"",
  action in [Action::"action"],
  resource is a in a::""
) when {
  (true && [action, ("" in "") in (Av8hxNw_88888888::"" in ""), [resource, "" in "", "" in "", "j" in "", "" in "", "" in "j"], [], ["", "" in "", "" in "\u{1}i", "" in "", "" in Av20088888888888::"", A88888888888888h::"jx" in A888888888888888::""], [false, "j", "", "", "", ""] in (Av8hxNw_88888888::"" in "")]) && [resource, ("" in "") in ("" in "j"), ["" in "چ", "" in "j", [], ["", "", "", "", "", ""], true in "", "" in ""], ("" in A888U8888888888h::"") in action, ("" in "") in (Av8h8h8888888888::"" in ""), [resource, "" in "", "" in "", "j" in "", "" in "", "" in "j"]]
};
