@AhJAA("njjj\u{15}jnjjjjb]\u{13}\r\0")
@pfffffff("))))))))))))))))))))))")
@t3VV0("")
@tPPPPPPPPPP2PPPP("")
@tPPPPPVVVVVVVVVV("")
@tPPPPPemOhhhhcff(")))))))))")
@tPPgPPP50000000P("")
@zV333("")
@zVVVV("")
permit(
  principal,
  action in [Action::"action"],
  resource in r::"\0\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}z\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\0\0&\0\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}"
) when {
  true && (principal == principal)
};
