@SI("\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\0")
@p("))))))))))))))))))))))))))))))))))))))")
@r("")
@rh2ggggPP("")
@sVVVVVVVVVA33u1("\0\0\u{5}")
@tPPPPPPPPPP2PPPP("")
@tPPPPPVVVVVVVVVV("")
@tPPPPPemOhhhhcff(")))))))))")
@tPPPPfIIIIIIIxIK("\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\0\0\0\0\0")
@tPPgPPP50000000P("")
@tPPrcknjPPP2PPPP("")
@zV0VV("")
@zVVVV("")
permit(
  principal is tgPPP50000000PPP,
  action in [Action::"A",Action::"A"],
  resource is tgPPP50000000PPP
) when {
  (true && (!(!(!3535908526261146130)))) && (!(!(!(-7072751903749595903))))
};
