@AYB("jjj")
@Ahhhh("j")
@Aq2("g")
@B("\0\0\u{5}")
@H3("")
@K("\n\n\n")
@L("")
@LYM("")
@LfY("")
@V("\0")
@Z("j")
@_("i")
@_hh("j")
@p(")))))))))")
@pLLLLLhhhgA("jjjjjjjjj\niii")
@pmjAAAAAAAAA("\ncei\njjjjbjjjjsAgg")
@r("))))))))))))j\nj")
@r3310("\0 ")
@r3u13053173("")
@r3u33333333("")
@tVVVVVVVVVVVVVVV("")
@zVVV0("")
@zVVVV("")
@zaYVV("")
permit(
  principal == a::"\0\0",
  action in [Action::"action"],
  resource in a::"\0\0"
) when {
  ((true && (a::"ccc" == ((8753308821594215944 * 8753159813895649657).contains(7668058320837114233)))) && 8753160913407277433) && (-7161677110969590628)
};
