@c8h8("j")
forbid(
  principal is a in a::"",
  action in [Action::"action"],
  resource is a in a::""
) when {
  (true && [action, ("" in "") in (Av8hxNw_88888888::"" in ""), [resource, "" in "", "" in "", "j" in "", "" in "", "" in "j"], [], ["", "" in "", "" in "\u{1}i", "" in "", "" in Av20088888888888::"", A88888888888888h::"jx" in A888888888888888::""], [false, "j", "", "", "", ""] in (Av8hxNw_88888888::"" in "")]) && [resource, ("" in "") in ("" in "j"), ["" in "", "" in "", [false, "j", "", "", "", ""], "" in "\u{1}i", "" in "", "" in a::""], ["", "" in "", "" in "j", [], ["", "", "", "", "", "j"], []], ["", "" in "", "" in "j", [], resource == "", "" in ""], ("j" in "") in ("" in "")]
};
