permit(
  principal == a::"jj",
  action in [Action::"nks-`"],
  resource is a in a::"jj"
) when {
  (true && [[action, action, At1j0::"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0i", Ahht1::"\0\0\0\0\0\0\0FFFFFFFFFFFFFFFFFF\0\0\0\0jpjj", Action::"nks-`", Ahh::"jj"].isInRange([Ahhfh::"\0\u{2}kk\0K\\ccccc", principal]), context, false, principal, nt00t::Ctttt::Ct000::Ctttt::"\0\0\0\0\0\07\07777\0\0\07\u{1}\0\u{1}\0T]ia", (!zng::"5j5\0dj7\u{1}\0\0\0\0\0\0\0\0\0\0\0\0\0\07\u{1}\0\u{1}") + (!resource)]) && Arr::"\0\0\0\0"
};
