forbid(
  principal in _0Ah::"",
  action == Action::"jjrjjjjjjrbjjjjjjcjjjjjjj",
  resource in _0Ah::""
) when {
  (true && (((Action::"jjrjjjjjjrbjjjjjjcjjjjjjj" == Action::"jjrjjjjjjrbjjjjjjcjjjjjjj") == (Action::"jjrjjjjjjrbjjjjjjcjjjjjjj" == Action::"jjrjjjjjjrbjjjjjjcjjjjjjj")) == ((Action::"jjrjjjjjjrbjjjjjjcjjjjjjj" == Action::"jjrjjjjjjrbjjjjjjcjjjjjjj") == (Action::"jjrjjjjjjrbjjjjjjcjjjjjjj" == Action::"jjrjjjjjjrbjjjjjjcjjjjjjj")))) && (((Action::"jjrjjjjjjrbjjjjjjcjjjjjjj" == Action::"jjrjjjjjjrbjjjjjjcjjjjjjj") == (Action::"jjrjjjjjjrbjjjjjjcjjjjjjj" == Action::"jjrjjjjjjrbjjjjjjcjjjjjjj")) == ((Action::"jjrjjjjjjrbjjjjjjcjjjjjjj" == Action::"jjrjjjjjjrbjjjjjjcjjjjjjj") == (Action::"jjrjjjjjjrbjjjjjjcjjjjjjj" == principal)))
};
