permit(
  principal,
  action == Action::"action",
  resource in a::"hhcn::r::ugnhhhch2@\0\0\0j.jjj"
) when {
  (true && (((Action::"action" == Action::"action") == (Action::"action" == Action::"action")) == ((Action::"action" == resource) == (Action::"action" == Action::"action")))) && (((a::"" == false) == (true in a::"")) == ((if action then A7hhfh::"da" else Action::"action") + (Action::"action" == 0)))
};
