forbid(
  principal is K3eh2 in Mfh::"",
  action in [Action::"============\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}jjjjjjj\u{3}"],
  resource is K3eh2 in Mfh::""
) when {
  (true && (Action::"============\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}jjjjjjj\u{3}" in ((Action::"============\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}jjjjjjj\u{3}" in Action::"============\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}jjjjjjj\u{3}") in (Action::"============\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}jjjjjjj\u{3}" in Action::"============\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}jjjjjjj\u{3}")))) && ([] in ((Action::"============\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}jjjjjjj\u{3}" in Action::"============\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}jjjjjjj\u{3}") in (false in s2fhh::"\u{7}\u{6}\u{6}\u{6}\u{6}\0")))
};
