@SI("\u{12}\u{12}\u{12}\u{12}2\u{12}")
@h("\u{1}\0\0\u{5}")
@pfffffff(")))))))))))))))))))))))))))))")
@rIeiI("\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}z\u{12}\n")
@rh2ggggPP("")
@tP2AggghPPPPemOh("jjj&jjjjj&\0\0\0\0")
@tPPPPPPPPPP2PPPP("")
@tPPPPffaffffffff("))))))))))\u{1}\0\0\0\0\0\0\0")
@tPPgPPP50000000P("")
permit(
  principal == pfffffPP::"",
  action == Action::"))))))))",
  resource == zVVVa::""
) when {
  ((true && Action::"") && (((Action::"" == Action::"") == (Action::"" == Action::"")) == ((Action::"" == Action::"") == (Action::"" in Action::"")))) && (tPffafffffffffff::"" == zVVVa::"")
};
