permit(
  principal is r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r3Xha in r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::AhhFF::"",
  action in [r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::Action::"action",r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::Action::"action",r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::Action::"action"],
  resource is r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r
) when {
  true
};
