@A("jj")
@AhhY("")
@Aq2("ggjjji")
@J2eeh("jji")
@K("\n\n\n")
@L("")
@LAA("\n\n\u{2}\0\n\n\n\n")
@LXY("ijjj")
@LYS("")
@LYX("")
@LYY("")
@V("\0")
@V00("\n\n\n\ncei\njjjjbjjjjs")
@Z("j")
@_LL("")
@ohhhhhhchhhKKK("\u{14}")
@pLLCCfnLLLLL("")
@pLLLL0YYYYYY("")
@pLLLLLLLLLLL("")
@pLLLLLLLLLLj("")
@pLLLLLLLLLZf("##")
@r("")
@y3("")
permit(
  principal == a::"\0\0\0",
  action in [Action::"action"],
  resource == a::"\0\0\0"
) when {
  (true && (!a::"\0\0\0")) && principal
};
