@A0("\u{5}")
@p("))))))))))))))))))))))))))))))))))))))")
@r("")
@rh2ggggPP("")
@tPPPPPPPPPP2PPPP("")
@tPPPPPemOhhhhchh("j&jj\0\0\0\0")
@tPPPPffaffffffff(")))))))))))")
@tPPgPPP50000000P("")
forbid(
  principal in zVVVk::"",
  action in [Action::"痗",Action::"",Action::"(0"],
  resource is zVVw3 in zVVVk::""
) when {
  ((true && (((tPgPPP50000000PP::"" has "") has "") has "")) && (((false has "\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}\u{12}jjjji\njjjjjjj\njhjjjjjj0") has "") has "")) && (!(!(!1302123112830210578)))
};
