@AYB("jjj")
@AhhY("")
@Aq2("egjjji")
@J2eeh("jji")
@K("\n\n\n")
@L("")
@LYX("")
@LYY("")
@V("\0")
@Z("j")
@_LL("")
@pLLhhhgAhhhh("jjjjj$j\njjjjjjjjj")
@pmjAAAAAAAAA("\ncei\nj")
@q("\n\n\n")
permit(
  principal == a::"\0\0",
  action in [Action::"action"],
  resource in a::"\0\0"
) when {
  ((true && (a::"ccc" == ((8753308821594215944 * 8753160913407277433).contains(8753160913407277433)))) && (-7161677261882951303)) && resource
};
