@Acddchrh("tjj[@jjj")
@AhhY("")
@H("\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}2\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}+j")
@H7777D77("\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}\u{7}")
@K("\n\n\n")
@L1000YY("")
@LAA("\n\n\u{2}\0\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\ncei\njjjjbjjjjsAggjjji")
@LLL("")
@LYX("")
@LYY("ZZZZZZjjjjbjjjjjjjjjbjjjjjjjjjjii\u{10}\0\0\0\0ZjZ?ZZjjjbj\0\0\0ZZi::ZZZZ\u{16}")
@Maf66("\u{6}\u{6}\u{6}\u{6}\u{6}ty##################\u{7}")
@V00("\0")
@Z("j")
@_("iZZi\n8ZZZZ\u{16}Z")
@lRRggg("**")
@pLLLLLLLLAAA("\n\n\n\n\n\n\ncem\njjjjbjjjjsAgg")
@pLLLLLLLLLLL("")
@pLLLLLLMLLLL("")
@r("gjAch\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}\u{6}ty########\u{1}\0\0\0\0\0\0\0")
@r3u10053173("ZZi\n0ZZZZ\u{16}ZZZZZZZjjjjbjjjjannotationsjjjjjiiZZi\n0ZZZZ\u{16}ZZZZZZ")
@r3u13053_63("")
@rh33N("")
permit(
  principal is a,
  action in [],
  resource == a::"\0\0\0"
) when {
  false && principal
};
