permit(
  principal == a::"",
  action in [Action::"action"],
  resource == a::""
) when {
  (true && (([false, Action::"action", Action::"action"].containsAll([a::"AhhN0bjjj", context, MffFm::"jj", Ahh20::"\0j", a::"AhhN0bjjj", false, AZhhh::""])) == ([false, Action::"action", Action::"action"].containsAll([a::"AhhN0bjjj", context, false, context, CjhhgA00::"\0\0\0jjjjj\0\0", principal, principal])))) && principal
};
