forbid(
  principal,
  action in [R::R::R::R::Ahhhh::R::Action::"action"],
  resource
) when {
  ((true && (R::R::R::R::Ahhhh::R::a::"jjijjjjjjjjjjlinksjjjjjjjjjjJjjjjj`ja\njjnjj2jjj\0\0\u{1d}\0\0" in [[false, false], principal])) && (R::R::R::R::Ahhhh::R::a::"jjijjjjjjjjjjlinksjjjjjjjjjjJjjjjj`ja\njjnjj2jjj\0\0\u{1d}\0\0" in R::R::R::R::Ahhhh::R::a::"jjijjjjjjjjjjlinksjjjjjjjjjjJjjjjj`ja\njjnjj2jjj\0\0\u{1d}\0\0")) && R::R::R::R::Ahhhh::R::a::"jjijjjjjjjjjjlinksjjjjjjjjjjJjjjjj`ja\njjnjj2jjj\0\0\u{1d}\0\0"
};
