@Cglh("")
permit(
  principal,
  action,
  resource
) when {
  true && {"AgYhhhhRhhhxqZ": {"A": principal, "r": {"vw3000133333z": a::"\0\0\0\0\0\0\0", "A": principal, "AgYhhhhRhhhxqZ": 7667978729021836394, "r": "jjj"}}, "r": {"AgYhhhhRhhhxqZ": v0730O000y3hN::"", "A": AhRhh::"z" == a::"\0\0\0\0\0\0\0", "r": context, "vw3000133333z": !a::"\0\0\0\0\0\0\0"}, "A": principal, "vw3000133333z": a::"\0\0\0\0\0\0\0"}
};
