@jwwwwww_wW("          jnjr")
@jwwwwwwwww("")
forbid(
  principal in a::"X2h0hhhhhhhhh ",
  action in [Action::"action",Action::"action",Action::"action"],
  resource in a::"X2h0hhhhhhhhh "
) when {
  ((true && ((("                        " == action) == Action::"action") == ((!true) is a))) && (if false then context else ((principal == principal) == (principal == principal)))) && ((a::"X2h0hhhhhhhhh " == a::"X2h0hhhhhhhhh ") == a::"X2h0hhhhhhhhh ")
};
