@A("")
@AhhFF("NNjjjjj")
@r("j$")
permit(
  principal is r,
  action in [],
  resource in r3Xha::""
) when {
  ((true && ((("TTTTTTTTTTTTTTTTTTTTTTTTTTT" == action) == (action || action)) == ((action || action) || (action || action)))) && (((action || action) || (principal || "\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}TTTTTTT")) || ((action || action) || (action || action)))) && (((action || action) || (action || action)) || ((action || principal) || ("\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}\u{1b}" == "\u{1b}")))
};
