permit(
  principal,
  action == dqqq::dqqq::dqqq::dqqq::dqqq::dqqq::dqqq::dqqq::d333::r::r::r::r::r::r::r::r::r::r::l::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::F::Fmmmmmmmmm::r::r::r::r::r::r::Gxxxxxxxx::Gxxxxxxxx::Gxxxxxxxx::Gxxxxxxxx::Gx3333333::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::A::r::Action::"action",
  resource
) when {
  true && (!dqqq::dqqq::dqqq::dqqq::dqqq::dqqq::dqqq::dqqq::d333::r::r::r::r::r::r::r::r::r::r::l::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::F::Fmmmmmmmmm::r::r::r::r::r::r::Gxxxxxxxx::Gxxxxxxxx::Gxxxxxxxx::Gxxxxxxxx::Gx3333333::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::r::A::r::Action::"action")
};
