@Ahbhh("\n\nj\u{19}")
@Ahhhhh("jjj\0\0\0\0\0\0YYYYYYYYYYYYYYYYY\u{16}\u{16}\u{16}")
@WYargm("n_cons\u{16}\u{16}\u{16}\u{16}\u{16}\u{16}\0)j\u{1}\0\0\0\0\u{1}\0\0\0\0YYYYYYY")
@kQQ("YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY\0\0j@\0\0&\n")
@kQQQQ("YYYYYYYYYYYYYzYYYYYYYYYYYYYYYYYYYY\u{16}\u{16}\u{16}")
@r("\n")
permit(
  principal,
  action,
  resource
) when {
  (true && "\u{16}\u{16}\u{16}\0)j\u{1}\0\0\0\0\u{1}\0") && action
};
