permit(
  principal == a::"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0jj0A\n?:\\iii\njjjjjjjjj~jjjjjjjjjjj\0jat",
  action in [Action::""],
  resource
) when {
  ((true && a::"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0jj0A\n?:\\iii\njjjjjjjjj~jjjjjjjjjjj\0jat") && false) && Ahhhhhhhm20::"Jjjj\0"
};
