permit(
  principal is a in a::"\0\0\0",
  action in [Action::"action"],
  resource
) when {
  ((true && (((resource == resource) == (resource == resource)) == ((resource == resource) == (resource == resource)))) && (((resource == resource) == (resource == resource)) == ((resource == resource) == (resource == resource)))) && (((true == z::z::r::r::I::IfffXf000000000::z::"") == principal) == principal)
};
