forbid(
  principal,
  action in [R::A::R::Action::"action"],
  resource
) when {
  ((true && (R::A::R::a::"jj\u{11}\u{11}\u{11}\u{11}jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj2jjj\0\0\0" in [R::A::R::a::"jj\u{11}\u{11}\u{11}\u{11}jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj2jjj\0\0\0", R::A::R::Action::"action", principal, action, Ahhhh::"k\0", R::A::R::a::"jj\u{11}\u{11}\u{11}\u{11}jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj2jjj\0\0\0", Ahhhh::"jj"])) && Aihhh::"jjj\0\0\0") && (!R::A::R::a::"jj\u{11}\u{11}\u{11}\u{11}jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj2jjj\0\0\0")
};
