@A0000000LLLL("")
@A00YYYYYY("")
@AhhY("")
@J2Ph9("")
@J2eeh("jji")
@K("\n\n\n")
@KAA("\n\u{2}\0\njji")
@KAAY010Y3YY("ߟ")
@KAacgAhhhhZ("jjjjsAgg")
@L("")
@L0c("j")
@LXY("")
@LYV("")
@LYY("")
@V("\0")
@V00("\0")
@Z("j")
@p("")
@pLL("")
@pLLLLLLAgAAA("\n\n")
@pLLLLLLLLL33("")
@pLLLLLLLLLLL("")
@r("")
forbid(
  principal,
  action == Action::"action",
  resource in a::""
) when {
  false && principal
};
