@A("jjjjjj")
@r("?")
permit(
  principal == r::r::r::r::r::r::r::r::A::r::a::"",
  action in [r::r::r::r::r::r::r::r::A::r::Action::"action"],
  resource == r::r::r::r::r::r::r::r::A::r::a::""
) when {
  ((true && r::r::r::r::r::r::r::r::A::r::a::"") && r::r::r::r::r::r::r::r::A::r::a::"c") && (((context || r::r::r::r::r::r::r::r::A::r::Action::"action") || resource) || ((false["AUghh"]) == r::r::r::r::r::r::r::r::A::r::a::""))
};
