forbid(
  principal == a::"",
  action in [Action::"action"],
  resource == a::"&[\u{14}\u{13}\u{1b} "
) when {
  (true && (if (!({"jj`jjjjNNN": "jj`jjjjNNN"}["V"])) then (("jj`jjjjNNN" in "jj`jjjjNNN") in (A::"" in "jj`jjjjNNN")) else (("jj`jjjjNNN" in "jj`jjjjNNN") in ("jj`jjjjNNN" in "jj`jjjjNNN")))) && (((A::"" in resource) in ("jj`jjjjNNN" in "jj`jjjjNNN")) in ((Ahu::"jj\0" in principal) in a::"&[\u{14}\u{13}\u{1b} "))
};
