@A("jj")
@A3_sh("Fjjjjj")
@Ah3p3("jb")
@Ahhhh("jjjjjjjjjjjjjjjjjjjjjjjjjj")
@Ahhhhh("j")
@N03_0("jjrjjjjrb")
@r("jjjj\n\0\u{7f}")
@r133h("")
@r3hhhhA0("\u{7f}")
@rhZ33l33ThZhh("\u{10}\0")
@rhZ33l33Z3hZh("jj")
@rhZ9a03_shhhh("jjj")
@rhg33l33hZhhG("\0")
@t9a03("")
@xjopnlQqnYh3133h("")
@xjoprlQqnYh3133h("")
permit(
  principal == a::"jjjjjjjjjjjjju",
  action in [Action::"jr"],
  resource == a::"jjjjjjjjjjjjju"
) when {
  true
};
