@A(")jjjjj[jj]jjjjjj&jjj\u{14}\u{14}")
@AYg("jjj")
@AhhY("")
@Aq2("ggj")
@J2eeh("jji")
@K("\n\n\n")
@KAA("\n\u{2}\0\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\ncei\nj\0")
@L("")
@LLL("")
@LXY("")
@LYX("")
@LYY("")
@UKLL("")
@V("\0")
@V00("\0")
@Z("j")
@_LL("")
@p00000000LLL("")
@pLLLL0YYYYYY("")
@pLLLLLLLLAAA("\n\n\n\n\n\n\ncei\njjjjbjjjjsAgg")
@pLLLLLLLLLLL("")
@pLLLLLLLLZfZ("#")
@pLLLYYAAAA20("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\ncei\njjjjbjjjjsAggjjji")
forbid(
  principal,
  action in [Action::"action"],
  resource
) when {
  (false && (!true)) && true
};
