forbid(
  principal in a::"",
  action == Action::"action",
  resource
) when {
  (true && (((Daaaaaaaaa::"" == Daaaaaaaaa::"") == (Daaaaaaaaa::"" == Daaabaaaaa::"")) == ((Daabaaaaaa::"" == DaaaaaahUh::"i\n}") == (Daaaaaaaaa::"" == Daaaaaaaaa::"")))) && (((Daaaaaaaaa::"" == A::"\0\u{11}") == (DaaaaVMaaa::"" == Kk1a::"")) == ((Daaaraaaba::"" == Daaaaaaaaa::"") == (DaaaaaahUh::"i\n" == Aaaaa::"")))
};
