@Cglh("")
permit(
  principal,
  action,
  resource
) when {
  true && {"r": {"r": context, "vw30002333333": !a::"\0\0\0\0\0\0\0", "AgYhhhhRhM0000": v0730O000y3hN::"", "A": AhRjh::"z" == a::"\0\0\0\0\0\0\0"}, "AgYhhhhRhM0000": {"r": {"AgYhhhhRhM0000": 7667978729021836394, "vw30002333333": a::"\0\0\0\0\0\0\0", "A": principal, "r": "jjj"}, "A": principal}, "vw30002333333": a::"\0\0\0\0\0\0\0", "A": principal}
};
