forbid(
  principal,
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("0.1")) == (decimal("0.1"))) then "" else "") == "")) && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (decimal("\0"))) == (if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))))) && ((if (false == false) then (decimal("\u{8}\u{8}")) else (if true then (decimal("0.1")) else (decimal("0.1")))) == (decimal("0.1")))
};
