permit(
  principal is a in a::"6",
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if false then (decimal("0.1")) else (decimal("0.1"))) else (decimal(""))) == (if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))))) && ((if ((decimal("0.1")) == (decimal("0.1"))) then (decimal("\0i")) else (if false then (decimal("0.1")) else (decimal("0.1")))) == (decimal("6[\u{16}6")))) && (a::"6" in a::"6")
};
