forbid(
  principal,
  action in [Action::"action"],
  resource
) when {
  ((true && ((if ((-1) == (-1)) then (if true then (-1) else (-1)) else (if false then (-1) else (-1))) == (if ((decimal("0.1")) == (decimal("0.1"))) then (-1) else (if false then (-1) else (-1))))) && ((if (false == false) then (if false then (-1) else (-1)) else (if true then (-1) else (-1))) == (if ((decimal("0.1")) == (decimal("0.1"))) then (-1) else (if false then (-1) else (-1))))) && ((if (false == false) then (if false then (-1) else (-1)) else (if true then (-1) else (-1))) == (if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (-1) else (-1)) else (-1)))
};
