permit(
  principal,
  action,
  resource is a
) when {
  (true && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))) == (if false then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))))) && ((if ((decimal("0.1")) == (decimal("0.1"))) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))) == (if ((ip("255.255.54.54/15")).isIpv4()) then (if true then (decimal("0.1")) else (decimal("0.1"))) else (if true then (decimal("0.1")) else (decimal("0.1")))))
};
