@C("")
@P("")
@r("")
permit(
  principal,
  action,
  resource
) when {
  ((true && ((if ((decimal("-421108.1217")) == (decimal("0.1"))) then (if true then (decimal("13743915.79")) else (decimal("-5995417003936.9729"))) else (if false then (decimal("58637175441116.3648")) else (decimal("0.1")))) == (if ((decimal("900721213964.2879")) == (decimal("-1395.9169"))) then (decimal("")) else (decimal(""))))) && false) && false
};
